### ISSUE TITLE
Monitor and touchpad settings in autostart segfault on wayland

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-config#1010]
##### Expected Behavior

No segfaults at login

##### Current Behavior

Executing ` lxqt-config-input --load-touchpad` and ` lxqt-config-monitor -l `  under wayland segfault as there is an option, while the command itself triggers a warning and is ok.
##### Possible Solution

Adding `X-LXQt-X11-Only=true` in `lxqt-config-input.desktop` in autostart, the monitor settings should load under kwin though.
##### Steps to Reproduce (for bugs)

1. Configure monitor and touchpad under X11
2. Log into wayland session
3. See  ` ls  /var/lib/systemd/coredump|grep input

##### System Information

* Distribution & Version: 2.0, all

**Comment by tsujan** [comment]
Closed in https://github.com/lxqt/lxqt-config/commit/2682058165c6382ad81711eef080c4cbdcf465c0
