### ISSUE TITLE
lxqt-config-appearance: Possible to select multiple palettes and then apply

### ISSUE THREAD

**Issue by isf63** [lxqt/lxqt-config#1048]
Under 'Qt Palette' it is possible to click "Load Palette", select multiple palettes, and then hit OK. When loading with multiple selected, I believe only the last one is applied, but in general it's nondeterministic.

##### Expected Behavior
Allowing for selecting more than one is necessary, to enable deleting multiple at a time.

Not sure what to do with "OK".

##### Current Behavior
Selecting multiple palettes and hitting OK either applies the last one or has unknown behavior.

**Comment by tsujan** [comment]
> I believe only the last one is applied, but in general it's nondeterministic.

No, the *current* item is applied (which is usually the last one, but not necessarily), and it's deterministic.

All styles should have ways to distinguish the current item, whether it's selected or not. In this case, only the selected current item is applied.

I guess you use Breeze, which has more than one design flaw. The following screenshots are taken with Fusion and Kvantum. In both, the current item is "KvAmbience", and it is applied.

![fusion](https://github.com/user-attachments/assets/55ea5b6b-fb50-4ff7-b814-8a0e50269ff9)

![kvantum](https://github.com/user-attachments/assets/16d27907-1cfe-4837-b587-3ef322d8689b)
