### ISSUE TITLE
QT5 apps ignore font and theme settings

### ISSUE THREAD

**Issue by NektoNektovich** [lxqt/lxqt-config#1063]
Linux 6.1.110, lxqt 2.0.0, liblxqt 2.0.0, lxqt-build-tools 0.13.0

I used xfce for many years, but I wanted to live with lxqt, and with version 2.0.0 I decided. everything seems to be good, but qt5 applications look terrible - with a huge, unchanging font and ignore design themes :( please fix it or at least tell me how to fix this nightmare???!!!!!! :'(
![qt5-problem](https://github.com/user-attachments/assets/ebb68ba7-29f5-4f22-b101-fe7e13254a89)

**Comment by stefonarch** [comment]
https://github.com/lxqt/lxqt/wiki/Building-from-source#qt5-support

Consider using "Discussions" for questions, thanks.

**Comment by NektoNektovich** [comment]
> https://github.com/lxqt/lxqt/wiki/Building-from-source#qt5-support
> 
> Consider using "Discussions" for questions, thanks.

I installed these three components: 
    libqtxdg 3.12.0
    libfm-qt 1.4.0
    lxqt-qtplugin 1.4.1
but the display of qt5 applications has not changed :( what is wrong? Do I understand correctly what will be fixed with the release of lxqt 2.1.0?

**Comment by stefonarch** [comment]
That shouldn't be any issue, it's ok from v2.0.0. on when the Qt6 port was finished.
There has to be something else - you don't use qt5ct or qt6ct no? 
You could also test a fresh user to cross check.

**Comment by NektoNektovich** [comment]
> Это не должно быть какой-либо проблемой, все в порядке с версии v2.0.0. on, когда порт Qt6 был завершен. Должно быть что-то еще - вы не используете qt5ct или qt6ct, нет? Вы также можете протестировать нового пользователя для перекрестной проверки.

When I realized that qt5 applications ignored font and theme settings, I tried to use qt5ct and qt6ct, but they did not work, saying that they were not configured. I couldn’t configure them and deleted them. if you say that it should work now, then perhaps my choice of the alt linux sisyphus distribution is to blame?

**Comment by tsujan** [comment]
> then perhaps my choice of ... is to blame?

Before blaming anyone, check whether your distro has provided you with installable packages for libqtxdg 3.12.0, libfm-qt 1.4.0 and lxqt-qtplugin 1.4.1, and that you've really installed them alongside the installable packages for libqtxdg 4.0.0, libfm-qt 2.0.2 and lxqt-qtplugin 2.0.0.

**Comment by NektoNektovich** [comment]
> > тогда, возможно, виноват мой выбор...
> 
> Прежде чем обвинять кого-либо, проверьте, предоставил ли ваш дистрибутив вам устанавливаемые пакеты для libqtxdg 3.12.0, libfm-qt 1.4.0 и lxqt-qtplugin 1.4.1, и действительно ли вы установили их вместе с устанавливаемыми пакетами для libqtxdg 4.0.0, libfm-qt 2.0.2 и lxqt-qtplugin 2.0.0.

libfm-qt 1.4.0 and lxqt-qtplugin 1.4.1 are not in Sisyphus, I installed them from the alt Linux p11 test repository. libqtxdg 4.0.0, libfm-qt 2.0.2 and lxqt-qtplugin 2.0.0 were on the system initially.

**Comment by stefonarch** [comment]
Most likely they are not installed correctly. Here's their path on arch, no idea about the pathes on your distro.

Check for `lxqt-qtplugin 1.4.1:
![image](https://github.com/user-attachments/assets/5de20688-1107-47d3-927c-97544a3c641a)
libfm-qt 1.4
![image](https://github.com/user-attachments/assets/87b42d7a-407d-4d16-967d-6ed07c84c01f)
 libqtxdg 3.12.0

![image](https://github.com/user-attachments/assets/7b523936-25b8-484d-938a-5f7ca2bca709)
