### ISSUE TITLE
The color of folders varies greatly in the file manager and on the desktop

### ISSUE THREAD

**Issue by NektoNektovich** [lxqt/lxqt-config#1068]
Linux 6.1.110, lxqt 2.0.0, liblxqt 2.0.0, lxqt-build-tools 0.13.0, papirus-icon-themes

The color of folders varies greatly in the file manager and on the desktop. Is this how it should be or is it a feature of the distribution? How can I make the color of folders on the desktop identical to the color in the file manager?
![fm](https://github.com/user-attachments/assets/171b8cff-ad7c-47eb-a4b5-8bd7f4070eae)
![rs](https://github.com/user-attachments/assets/0113e879-222e-4a5d-94c0-9af3201a9eea)

**Comment by tsujan** [comment]
Not related to LXQt.

Your icon set has different colors for 48px and 32px folder icons.

**Comment by NektoNektovich** [comment]
> Not related to LXQt.
> 
> Your icon set has different colors for 48px and 32px folder icons.

Weird. when I used xfce, I used the same papirus-icon-theme-orange package, the color of the folders was orange everywhere and the size of the folders was identical 🤔 I believe that the color of the folders in lxqt on the desktop depends on the light/dark theme. with a light icon theme, the folders on the desktop are white, although there should always be orange ones everywhere 🤔
