### ISSUE TITLE
Some debug messages are marked for translations

### ISSUE THREAD

**Issue by Fat-Zer** [lxqt/lxqt-config#1075]
There is a couple of [debug messages][1] marked for translation. Was it just a mistake or are they supposed to be actually delivered to the user in some over way? 

PS: as a reminder `qDebug()` calls and messages are usually removed completely when targeting a release build.

[1]: https://github.com/lxqt/lxqt-config/blob/beb8448cc3f4f2631a81873c74bbc846f0e679ec/lxqt-config-monitor/loadsettings.cpp#L107

**Comment by tsujan** [comment]
No mistake. See `lxqt-config-monitor --help`

**Comment by Fat-Zer** [comment]
> No mistake. See `lxqt-config-monitor --help`

@tsujan, but assuming those messages are meant for the user, why use qDebug()? qInfo() would be more appropriate choice than, isn't it? And if so why only this two messages are translated and not others?

> PS: as a reminder qDebug() calls and messages are usually removed completely when targeting a release build.

I was a bit wrong actually, you have to supply `-DQT_NO_DEBUG_OUTPUT` for that and lxqt's build system doesn't do it now.

**Comment by tsujan** [comment]
> And if so why only this two messages are translated and not others?

Because Wayland is special. We show a message dialog with the GUI if needed. These translations exist for the sake of completeness.

**Comment by Fat-Zer** [comment]
I won't insist either... though here I can't fully comprehend your logic...

**Comment by tsujan** [comment]
LXQt's Monitor Settings works with kwin_wayland but not with other Wayland compositors. We just wanted to make sure that the user would be informed; nothing more.
