### ISSUE TITLE
Keyboard switch layout limited to "Left and Right Alt While Pressed" making it unusable 

### ISSUE THREAD

**Issue by petran79** [lxqt/lxqt-config#1079]
I am using OpenSUSE TW 15.6, kernel 6.11.6, LXQT 2 from their repo. 

When I added a second language next to English, there is no option to choose a convenient shortcut to switch layout, like ctrl+shift for example. Just Left Alt while pressed, right alt while pressed, right alt while pressed. Tried changing the buttons in sessions.conf file, but it does not make any difference.

Is there any other way to add for example alt+shift to switch the layout?

**Comment by stefonarch** [comment]
In `lxqt-config-input` you should be able to choose between all those:
https://man.archlinux.org/man/xkeyboard-config.7#Switching_to_another_layout

**Comment by petran79** [comment]
thanks. Edited session. conf and now I switch with alt+Ctrl  and it works. though in keyboard config it appears as None, together with alt press options below.
