### ISSUE TITLE
cant set what i want a display to do when connected

### ISSUE THREAD

**Issue by guinea7pig** [lxqt/lxqt-config#1083]
i have a old laptop that im running lxqt, whene i connect display over vga it atoimaticly mirrors the display witch is a problem for a 16:9 displaying on a 4:3 display. even if i set it on a 4:3 resaltion it still glitches out. i have seen a menu of what you want to do with your screen come up once, for exsample it asks if you want to mirror the display or only putting it on monitor, for me putting it only on the monitor woks but i cant select it becuse the seconed i plug it in it starts mirroring instead of bringing up a menu, i have looked into the settings and there was no option to set what you want a screen to do on connect

##### Expected Behavior
 should open a up a menu telling how you want to connect the display

##### Current Behavior
 both the screen on my laptop and the monitor glitch out

##### Steps to Reproduce (for bugs)

1.  
2. 
3. 
4. 

##### Context
 use the screen with my laptop

##### System Information

* Distribution & Version:  debain 12
* Kernel: 
* Qt Version: 
* liblxqt Version: 
* lxqt-build-tools Version: 
* Package version:

**Comment by tsujan** [comment]
Which version of LXQt?

And are you sure you save your settings in LXQt Monitor Settings?

**Comment by guinea7pig** [comment]
i will check when i get home

**Comment by guinea7pig** [comment]
2.1.1

**Comment by tsujan** [comment]
And the second question?

**Comment by guinea7pig** [comment]
i did have a monitor setting saved but deleting it didnt help my problem
