### ISSUE TITLE
[Appearance] Breeze theme "missing" for gtk3 (showing for gtk2)

### ISSUE THREAD

**Issue by mpmc** [lxqt/lxqt-config#378]
**OS:** 
Debian unstable - with lxqt snapshots repo at lxqt.debian.net

**Issue:** 
The breeze theme isn't showing as an option for gtk3 but it IS for gtk2, I believe I have all the correct packages installed..

![no_theme](https://user-images.githubusercontent.com/2352508/50552734-c49e2300-0c91-11e9-832f-89a8d1da6278.png)

![breeze](https://user-images.githubusercontent.com/2352508/50552738-cbc53100-0c91-11e9-86ac-0e182bf67a11.png)

**Notes:**
After noticing this bug and chatting with @agaida, I installed adwaita themes & it shows up for both gtk versions.

**Comment by agaida** [comment]
Valid bug with an easy solution - so upstream or debian should change their evil ways :dark_sunglasses: 
![](https://i.imgur.com/f23vrvh.png)

just link one of the gtk-3.xy to gtk-3.0 and be done with. Dunno how it looks in other distributions.

**Comment by yan12125** [comment]
Issue reproduced on Arch Linux.
```
$ pacman -Ql breeze-gtk | grep gtk-3
breeze-gtk /usr/share/themes/Breeze-Dark/gtk-3.18/
breeze-gtk /usr/share/themes/Breeze-Dark/gtk-3.18/gtk.css
breeze-gtk /usr/share/themes/Breeze-Dark/gtk-3.20/
breeze-gtk /usr/share/themes/Breeze-Dark/gtk-3.20/gtk.css
breeze-gtk /usr/share/themes/Breeze/gtk-3.18/
breeze-gtk /usr/share/themes/Breeze/gtk-3.18/gtk-dark.css
breeze-gtk /usr/share/themes/Breeze/gtk-3.18/gtk.css
breeze-gtk /usr/share/themes/Breeze/gtk-3.20/
breeze-gtk /usr/share/themes/Breeze/gtk-3.20/gtk-dark.css
breeze-gtk /usr/share/themes/Breeze/gtk-3.20/gtk.css
```
And adding the symlink also "fixes" the issue on Arch Linux.

**Comment by stefonarch** [comment]
Looks like solved:
![schermata-19-18-31-12](https://user-images.githubusercontent.com/10681413/96479527-62812a00-1239-11eb-978d-c60205526142.png)
