### ISSUE TITLE
lxqt (non)working issues

### ISSUE THREAD

**Issue by odoncaoa** [lxqt/lxqt-config#387]
Can't find any other obvious place to point out these problems w/'lubuntu 18.10 lxqt', so I'll try to make them known here.
  Problem 1) Everytime one double clicks on a desktop included icon, there appears
             an popup mandating a user selection 'open' 'execute' or 'cancel' dialog
             and there does not appear to be an obvious way to have such a 'feature'
             turned off!?
  Problem 2) Any time the PCManFM-QT File Manager is used during the course of
             moving or copying an original file to a preexisting destination file,
             one is presented with a 'File exists' error, and the operation will
             not be executed.
  Problem 3) When a user selects a 'rename' label via a right click on a desktop
             icon, and actually enters a new display 'label name', the associated
             desktop icon disappears.
  Problem 4) There is no obvious way a user can associate a new icon with a desktop application
             via the ~/Desktop/appname.desktop mechanism.
                          
All of the issues pointed out here, should not be in effect, unless a user selects such 'timid' settings at installation time! If 'Windoze' operations are to be put into effect, then put such a mandate in at installation time. It is unreasonable for the rest of the user world to have no way to change the default working behavior, from those being targeted as 12 year old users; therefore! When I double click on a directory homed icon, I don't want to have to answer such a stupid question each time! Make such non-sense an opt-in feature! And, There should be a tree centric directive, so that the PCManFM-Qt view is thereby set to be the default view, for the specified directory, and every other directory for which it is an antecedent! These noted issue are all giant pains in the ass for actual grown up working users!             
Hoping for correlational changes. Cheers
odoncaoa

**Comment by tsujan** [comment]
Please don't report Lubuntu/Ubuntu problems here!

**Comment by agaida** [comment]
gosh, i should really add the .github dir to the newly created trackers :) - and mind the downstream thing there.
