### ISSUE TITLE
LXQt with HiDPI is a mess until the dpi setting is fixed

### ISSUE THREAD

**Issue by agaida** [lxqt/lxqt-config#401]
##### Expected Behavior
At least it should be possible to set up LXQt in a way that renders Qt and Gtk programs usable

##### Current Behavior
It isn't possible - The user has the choice to make Qt or GTK looking good and usable. The problems are only about font sizes - everything else is fine. Can't resist to rant a bit. Will provide screenshots and settings.

##### Possible Solution
We should fix it as soon as possible. Maybe fixing our DPI-Settings would be a good idea.

##### Steps to Reproduce (for bugs)
1. Buy a HiDPI Monitor  and start your installation 

##### Context
Main Problem - we have only one Fontsize we can change - it seems that it is not enough.

##### System Information
current git (kwin, xfwm4, openbox behave similar fugly)

**Comment by stevexyz** [comment]
> Is it really such a problem to make the damn dpi switch working - that would be enough in first place? Right now i solve the not working thing with:
> 
> ```
> % cat .Xresources 
> Xft.dpi: 120
> ```

I even reinstalled Debian testing with testing installer thinking that upgrade was ruining everything instead this setting made it usable! (even if still messing around with menu fonts etc...)

Thank you!

**Comment by stevexyz** [comment]
PS: installing the firmware-amd-graphics package also solved the issue, even with a better screen resolution...

**Comment by agaida** [comment]
erm - yes - a working and well configured graphics driver is helpful sometimes :sunglasses:

**Comment by tsujan** [comment]
This report was a result of @agaida's mistaking HDPI with something else (as he said, " we have only one Fontsize we can change"). https://github.com/lxqt/lxqt-config/issues/402 is a valid report but no one added the required settings.

**Comment by probonopd** [comment]
> In fact, the only problem is in the KWin title-bar, which isn't our fault.

Was this ever been solved? KWin seems to ignore `QT_SCALE_FACTOR=2`.

**Comment by redtide** [comment]
Not sure if the right place, but after an Archlinux update (including LXQt 1.0.0 but might be something else) some (not all) Qt apps was displayed with a bigger UI size (not just fonts), I guess the not affected ones haven't hidpi scaling enabled.
If someone else have/had some troubles by setting `QT_SCALE_FACTOR`, I had also to set `QT_AUTO_SCREEN_SCALE_FACTOR` to 0 to get it to work, so in my case I've set `~/.config/lxqt/session.conf` like this:
```ini
[Environment]
QT_AUTO_SCREEN_SCALE_FACTOR=0
QT_SCALE_FACTOR=1.0
```

**Comment by tsujan** [comment]
> after an Archlinux update... Qt apps was displayed with a bigger UI size...

Thanks for telling us about it! They may have forced `QT_AUTO_SCREEN_SCALE_FACTOR=1` somehow. If so, not all screens will be affected.

For now, my screen is like before (I have the latest git LXQt). If it's changed after a Manjaro update, I'll add a comment here.

And yes, `QT_AUTO_SCREEN_SCALE_FACTOR=0` should restore it. The user could add it to `LXQt Session Settings → Environment` if he wants it only with LXQt.

**Comment by tsujan** [comment]
BTW, [Qt doc](https://doc.qt.io/qt-5/highdpi.html) itself says, "However, these options may result in some scaling or painting artifacts." Forcing `QT_AUTO_SCREEN_SCALE_FACTOR=1` is a good idea (LXQt hasn't done it). The scale factor needs to be chosen by the user and "X_AUTO_Y" is always problematic.

**Comment by redtide** [comment]
Someone makes me notice that Qt was getting a scale factor of 2.0, which was incorrect and I had to force it to 1, so I wonder from where it comes from.
