### ISSUE TITLE
Poor user experience in lxqt-config-brightness

### ISSUE THREAD

**Issue by AlpacaRotorvator** [lxqt/lxqt-config#404]
I'm running lxqt on a laptop and I found the way the brightness controls work to be very suboptimal. My main gripes with it currently are:

*  There's no telling what each control does. The user has to move them around to get an intuition of their function.

* The dial-style control is very unwieldy on a trackpad, resulting on me swinging it around violently or unintentionally letting go of it while trying to fine tune.

* The way it currently works you can't easily try a setting that alters both controls. You have to move one control, save your configuration, then tweak the other one, save, then perhaps tweak the first one again, save, and so forth. The modal dialog is just too disruptive.

I'm no UX expert, but what I suggest to alleviate those problems is:

* Individual labels for each control.

* Make the control that is currently a dial(brightness?) into a slider like the other one(backlight?).

* This is the trickiest of the three. On one hand the user should be able to move the controls around and immediately see what the screen would look like, on the other hand we want a failsafe in case he accidentally sets his screen too bright/dark, but it shouldn't hassle the user too much mid-tuning like it does now.

One solution I can think off the top of my head would be do away with the modal popup and just have an "Apply/Save" button on the main window. Then have a timer running that resets every time the user changes the value of a control, and if the timer expires before the user clicks the apply button it automatically reverts to the previous value.
 
Not sure if relevant here but, just in case, I'm running LXQt 0.12 on Qt 5.10.1.

**Comment by selairi** [comment]
Hi, I have done some changes in the UI:
![lxqt-config-brightness-ui](https://user-images.githubusercontent.com/1163139/79002647-2fa2fe80-7b51-11ea-9c74-470656bf76ab.png)

What do you think?

**Comment by tsujan** [comment]
@selairi 
Your screenshot is much better than the current GUI.

**Comment by selairi** [comment]
I have added reset, increase and decrease buttons:
![bajarbrillo](https://user-images.githubusercontent.com/1163139/79051635-6fd9ae00-7c31-11ea-8037-bdb7ba3e9ee9.png)
Suggestions?

**Comment by tsujan** [comment]
@selairi
IMO, it's perfect.

BTW, I'll test your last commit at https://github.com/lxqt/lxqt-powermanagement/pull/189 soon.

**Comment by tsujan** [comment]
Closed in https://github.com/lxqt/lxqt-config/commit/3421fb5ad8d4b0de1a200391f4727a691031ebfe
