### ISSUE TITLE
After set new wallpaper with pcmanfm-qt, wallpaper will not update without trigger

### ISSUE THREAD

**Issue by ncc-1701-a** [lxqt/lxqt-config#461]
Hi.
I use the dynamic wallpaper (xplanetFX), which use the external script to update wallpaper.
I decide to test updating wallpaper with terminal:
pcmanfm-qt --set-wallpaper=/home/user/picture.jpg --wallpaper-mode=fit

##### Expected Behavior

Wallpaper should update immediately. 

##### Current Behavior

When cursor remain over any window region, wallpaper will not update.
Wallpaper will update after mouse cursor move over free (unoccupied with any window) desktop space.

##### Steps to Reproduce (for bugs)

1. Use any terminal. Set the mouse cursor under any window region;
2. Use command: pcmanfm-qt --set-wallpaper=FILE --wallpaper-mode=MODE
3. Do not move the mouse cursor (wallpaper will not update)
4. Move the mouse cursor over free (unoccupied with any window) desktop space: wallpaper will update.

##### System Information

* Distribution & Version: 
Debian Buster (testing)
* Kernel: 4.19.04 (amd64)
* Qt Version: 5.11
* liblxqt Version: 0.14.1-1
* lxqt-build-tools Version: 0.6.0-2
* Package version: 

Additional info:
Window manger: openbox or xfwm.

P.S. sorry for my bad English

**Comment by tsujan** [comment]
Confirmed! Thanks for reporting!

**Comment by tsujan** [comment]
BTW, we'd appreciate it if, in future, you report issues about pcmanfm-qt at its issue tracker: https://github.com/lxqt/pcmanfm-qt .

**Comment by ncc-1701-a** [comment]
Oops, understand (wrong browser bookmark confused me).

**Comment by tsujan** [comment]
There was no need to close this. Do you want to open it at pcmanfm-qt?

**Comment by tsujan** [comment]
OK, you did :)

**Comment by jubalh** [comment]
Referencing: https://github.com/lxqt/pcmanfm-qt/issues/935
