### ISSUE TITLE
LxQt Locale configuration no option for bengali or Bangladesh

### ISSUE THREAD

**Issue by priojeetpriyom** [lxqt/lxqt-config#483]
##### Expected Behavior

At least Region and Time option for Bangladesh should be available.

##### Current Behavior

No option in Region and Time option for Bangladesh should be available.
![image](https://user-images.githubusercontent.com/19343030/58689385-de34bb00-8354-11e9-8e97-da83e7b1e416.png)

##### Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

##### System Information

* Distribution & Version: 
* Kernel: 5.0.0-13
* Qt Version: 5.12.2
* liblxqt Version: 
* lxqt-build-tools Version: 
* Package version:

**Comment by tsujan** [comment]
On Debian Buster ISO I can find it:

![locale](https://user-images.githubusercontent.com/981076/58706113-5be4df00-83c6-11e9-8655-64c489ce92cd.png)

So, it isn't an LXQt issue but a matter of installing something.

Feel free to add comments to this closed issue — I'm also curious what should be installed.

**Comment by tsujan** [comment]
My bad; it's on my Manjaro installation too:

![BD](https://user-images.githubusercontent.com/981076/58708009-c77d7b00-83cb-11e9-94ca-7eda16b3e51a.png)

The string "BD" should be typed, not "Bangladesh". Of course, perl-datetime packages should have been installed.
