### ISSUE TITLE
Tooltips aren't informative

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt-config#494]
##### Expected Behavior

Tooltips are usually used to add something that doesn't exist in the GUI. A desktop file can contain a "Comment" section and the main menu (of lxqt-panel) shows it. Why not showing it here?
##### Current Behavior

In the case of lxqt-config, tooltips only show full names. OK, that's good because the GUI names may be elided but it isn't enough.
##### Context

My recent obsession with tooltips in libfm-qt (done).
##### System Information

Latest git

**Comment by tsujan** [comment]
BTW and just as a reminder, lxqt-panel's main menu apparently prefers GenericName to Comment for the tooltip; it shows Comment only when there's no GenericName . That's far from ideal, IMO.

**Comment by agaida** [comment]
@tsujan - your are absolutely right, no discussion about :)

**Comment by tsujan** [comment]
Good to know that it isn't a problem only from *my* perspective :)
