### ISSUE TITLE
Something is changed with Qt 5.13?

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt-config#499]
After I recompiled lxqt-config against Qt 5.13, I saw that its side-panes became too wide. This screenshot is taken with Breeze but the problem exists with all styles:

![lxqt-config](https://user-images.githubusercontent.com/981076/61176250-e37f5980-a5d2-11e9-80f5-a86cf4f5b049.png)

@yan12125, I know you have Qt 5.13; do you see a similar change?

**Comment by tsujan** [comment]
Actually, it's related to liblxqt's `ConfigDialog` and I can see it everywhere `ConfigDialog` is used. If it's confirmed, I'll close this and open another issue at liblxqt. If not, I should find the reason why I see it after closing this issue.

**Comment by yan12125** [comment]
Looks like it's indeed a liblxqt issue. Here's a screenshot of lxqt-config-session:

![圖片](https://user-images.githubusercontent.com/1937689/61179082-d3e12e80-a62d-11e9-8242-4eb1fd75f446.png)

On my machine lxqt-session is compiled against qt5-base 5.12.3-2 and run against qt5-base 5.13.0-7.

BTW I use KvMojaveLight theme of Kvantum.

**Comment by tsujan** [comment]
@yan12125 

Thanks! It seems that running against Qt 5.13 is enough for reproducing it.

Next job: looking for a needle in a haystack ;)

**Comment by tsujan** [comment]
For me, today was one of those days that several problems show up out of nowhere. Monospace fonts couldn't be made bold by Qt after yesterday's upgrades, VirtualBox stopped working, I found a bug in FeatherPad, and this issue! All are fixed, at last.

As for the current issue, I fixed it by adding the following method to `liblxqt` → `lxqtpageselectwidget.cpp`:

```c++
QSize PageSelectWidget::sizeHint() const
{
    const int f = 2 * frameWidth();
    return viewportSizeHint() + QSize(f, f);
}
```

Now, this is logical but the question arises as to why it wasn't needed before — or why it's needed with Qt 5.13.

A side note: We shouldn't have added the scrollbar width in `PageSelectWidget::viewportSizeHint()` but only in `PageSelectWidget::sizeHint() `, although the end result would be the same for us.

**Comment by tsujan** [comment]
I found the cause.

In Qt 5.13, `QAbstractScrollArea::sizeHint()` is changed. Now, it uses these 2 booleans to decide if the scrollbar thickness should be added to the width/height:

```c++
const bool vbarHidden = d->vbar->isHidden() || d->vbarpolicy == Qt::ScrollBarAlwaysOff;
const bool hbarHidden = d->hbar->isHidden() || d->hbarpolicy == Qt::ScrollBarAlwaysOff;
```

Previously, they were just `d->vbarpolicy == Qt::ScrollBarAlwaysOn` and `d->hbarpolicy == Qt::ScrollBarAlwaysOn`, which were wrong.

However, the new conditions are wrong too because `isHidden()` is `false` most of the time. As Qt doc [says](https://doc.qt.io/qt-5/qwidget.html#isHidden):

```
isHidden() implies !isVisible(), but a widget can be not visible and not hidden at the same time. This is the case for widgets that are children of widgets that are not visible.

Widgets are hidden if:

they were created as independent windows,
they were created as children of visible widgets,
hide() or setVisible(false) was called.
```

So, the new code adds the scrollbar thickness to the width if the scrollbar isn't hidden explicitly (which is the case for us and in many codes).

Anyhow, the above-mentioned workaround is good for all versions of Qt. I'll make a PR.

NOTE: I'm not good at reporting bugs to Qt developers.

**Comment by tsujan** [comment]
In short, Qt had an old bug that compensated for our mistake. Now it has a bug that can afflict correct codes too. So, the code needs to be self-sufficient.
