### ISSUE TITLE
lxqt-config-brightness: Use native backlight control instead of fake brightness controll when available

### ISSUE THREAD

**Issue by lupinix** [lxqt/lxqt-config#511]
If native backlight control is available, a slider in lxqt-config-control allows to use it instead of the "faked" brightness control. However, this is not the case when we run lxqt-config-brightness with -i or -d to decrease/increase brightness using command line. I request to add that functionality here, too.

The main reason: lxqt-config-brightness -d/-i is used for the keyboard shortcuts for brightness controll. As a result, using the shortcuts, the user always ends up with the faked brightness control, even when the native one is available.

**Comment by selairi** [comment]
Yes. It should be fixed. Lxqt backlight control is only used in GUIn only.
I would try to fixed.

**Comment by lupinix** [comment]
Thanks for investigating :)

**Comment by selairi** [comment]
There is a new pull request,  #521, that solves this problem. It must be accepted in master branch. Be patient.

**Comment by shlyakpavel** [comment]
The PR above is merged. Can we close the issue?

**Comment by agaida** [comment]
We can - the only thing left is to fix the ~~fucking ugly~~ not so usable interface.

**Comment by tsujan** [comment]
> the only thing left is to fix the not so usable interface.

It needs a little more love:

![brightness](https://user-images.githubusercontent.com/981076/63965802-304dbf80-caaf-11e9-9b73-b7bbd8eb95ef.png)

Shouldn't be hard. First remover that dial, then add ticks and numbers to the slider; problem solved.

**Comment by agaida** [comment]
right - i'm only mentioned it

**Comment by selairi** [comment]
I think that this issue should be closed.

**Comment by tsujan** [comment]
I'll close it after https://github.com/lxqt/lxqt-config/pull/612 is merged. Thanks for the reminder!

**Comment by tsujan** [comment]
Closed in https://github.com/lxqt/lxqt-config/pull/612
