### ISSUE TITLE
Unable to translate "Mouse and tauchpad" on Weblate

### ISSUE THREAD

**Issue by ito32bit** [lxqt/lxqt-config#528]
##### Expected Behavior

I want to translate "Mouse and tauchpad" into Japanse on Weblate.

Screenshot 1:
![config-input_ja_mark](https://user-images.githubusercontent.com/52656419/63665901-530a7a80-c808-11e9-8a86-2ec0195a3b7f.jpg)

Screenshot 2 (LANG=C):
![config-input_en_mark](https://user-images.githubusercontent.com/52656419/63665908-59005b80-c808-11e9-84db-07474f902506.jpg)

##### Current Behavior

I don't found the strings to translate on Weblate.
https://weblate.lxqt.org/projects/lxqt/lxqt-config-input/ja/

Strings:

	Mouse and Touchpad
	Device
	Acceleration speed
	Single clock to activate items
	Natural Scrolling
	Tap to drag
	Scrolling
	Disabled
	Two-Finger
	Edge
	Button

##### Possible Solution

"lxqt-config-input.ts" does not include strings of  "touchpadconfig.ui".  
"lxqt-config-input.ts" is old. This date is 23 Jun 2018.  
I think you need to update "lxqt-config-input.ts".

https://github.com/lxqt/lxqt-config/blob/master/lxqt-config-input/translations/lxqt-config-input.ts  
https://github.com/lxqt/lxqt-config/blob/master/lxqt-config-input/touchpadconfig.ui

##### Steps to Reproduce (for bugs)

1. Open  https://weblate.lxqt.org/projects/lxqt/lxqt-config-input/ja/

##### Context

I can't use "Mouse and Touchpad" in japanese.

##### System Information

* LXQt Version: 0.14.1 (add-apt-repository ppa:lxqt/ppa)

* Distribution & Version: Ubuntu 18.04.3 LTS
* Kernel: 4.15.0-58-generic
* Qt Version: 5.9.5
* liblxqt Version: 0.14.1
* lxqt-build-tools Version: 0.6.0-0ubuntu1
* Package version: lxqt-config/bionic,now 0.14.1-0ubuntu1

**Comment by ito32bit** [comment]
Today, the strings on Weblate has been updated. Thank you.

**Comment by tsujan** [comment]
Thanks for your patience! Yesterday, a huge amount of updates were made by @agaida.
