### ISSUE TITLE
Suggestion: Separate lxqt-config-appearance from lxqt-config and release it as a standalone package

### ISSUE THREAD

**Issue by nexusanphans** [lxqt/lxqt-config#559]
Given that LXDE's [LXAppearance](https://wiki.lxde.org/en/LXAppearance) package is popular enough to be used independently without other LXDE components by the linux communities[1][2][3][4][5][6], I don't see why its LXQt analogue, `lxqt-config-appearance`, is not provided as a standalone package as well. Both programs deal with theming issue, with the latter being able to configurate Qt themes alongside GTK ones. Installing `lxqt-config-appearance` alone will provide one tool for configuring two themes. `lxqt-config-appearance` is currently bundled in `lxqt-config` package. Henceforth, a user needing only the former needs to install the whole package of the latter.

![](https://i.stack.imgur.com/orEDc.png)

##### Expected Behavior
`lxqt-config-appearance` to exist as a separate package and can be installed independently out of other LXQt components.

##### Current Behavior
`lxqt-config-appearance` is bundled with other components in `lxqt-config` package.

##### Possible Solution
- Separate `lxqt-config-appearance` from `lxqt-config` and release it as a standalone package.
- Maybe even rebrand it as `lxqt-appearance` so that it can be more easily identified by those familiar with LXDE.

##### Context
This can be useful for those who are already familiar with LXappearance or LXDE, or only need the appearance config for configurating themes and not the other settings and programs that come as part of `lxqt-config` by default. Given the popularity of LXappearance, it may be a good idea to make the appearance config modular as well. Meanwhile, there are other components that logically can be assumed as part of `lxqt-config` but already exist as standalone packages, such as `lxqt-admin`, `lxqt-notificationd`, and `lxqt-powermanagement`, and this can be put as an argument to implement this suggestion.

##### References
1. [ArchWiki page](https://wiki.archlinux.org/index.php/GTK) listing LXappearance as a themer for GTK.
2. [Ubuntu Forum page](https://ubuntuforums.org/showthread.php?t=2208537)
3. [r/unixporn subreddit page 1](https://www.reddit.com/r/unixporn/comments/65ebd0/how_to_set_window_themes_for_i3/)
4. [r/unixporn subreddit page 2](https://www.reddit.com/r/unixporn/comments/8g95m3/how_to_change_gtk3_themes_inside_of_openbox/)
5. [r/unixporn subreddit page 3](https://www.reddit.com/r/unixporn/comments/1vl1g2/archi3_how_do_i_change_the_look_of_my_scrollbars/)
6. Or really just look at the internet

**Comment by tsujan** [comment]
> lxqt-config-appearance is bundled with other components in lxqt-config package.

That "bundling" is not arbitrary. Remove it and you'all have a poor or unusable app.

You could use lxqt-config-appearance outside LXQt by using its dependencies, especially by having `lxqt-qtplugin` and setting `QT_QPA_PLATFORMTHEME` to `lxqt`.

**Comment by nexusanphans** [comment]
How to install `lxqt-config-appearance` without installing the whole `lxqt-config`?

**Comment by tsujan** [comment]
The whole lxqt-config is a 300-KiB package here.

We can't damage LXQt integrity. LXQt is different from LXDE. "Appearance" means Qt + LXQt appearance first and foremost.

**Comment by palinek** [comment]
@nexusanphans All you're suggesting here is about packaging...do downstream. Please, talk to your distro maintainers.

**Comment by agaida** [comment]
@palinek - the answer is basically the same - as @tsujan mentioned - splitting out the appearance part will not change anything about used dependencies - so in the end it doesn't make a notable difference (Also called "unjustified waste of downstream maintainer time").

**Comment by tsujan** [comment]
@agaida I skipped a fact: Some people may think that appearance = GTK appearance. To style Qt5 apps, one needs a Qt style plugin. So, LXQt appearance app doesn't make sense without LXQt's Qt plugin, while LXDE's appearance app might have made sense everywhere.

**Comment by agaida** [comment]
Right
