### ISSUE TITLE
[lxqt-config-monitor]Add an fast config option to have 2 - 1 screen disposition

### ISSUE THREAD

**Issue by papoteur-mga** [lxqt/lxqt-config#573]
The tool allows to fast config duplicated screen, either one or the other and extended. The extended presumes that the primary screen is at left and the other is at right.
There no reason that the primary is not presumed to be at right and the other at left. Please add an option 2 - 1 Inverse extended.

**Comment by tsujan** [comment]
`lxqt-config-monitor` already allows any alignment. Use its latest git because some bugs are fixed there.

**Comment by papoteur-mga** [comment]
Hello,
Even if I don't use the latest snapshot, i have checked the code 
https://github.com/lxqt/lxqt-config/blob/2029fd0b9743c7f9d7d495c127e3423edb2ee5c0/lxqt-config-monitor/fastmenu.cpp#L178
and I don't see any **fast option** which is new  in relation to the version I use.
I know that I can manually choose a disposition which suit my needs. But this issue is for adding an option in fast options. I don't consider it as a bug but an enhancement request.

**Comment by tsujan** [comment]
You set up you desired alignment and save it. Then, you could restore it fast.

**Comment by tsujan** [comment]
That fast options are the most common ones. Screens can also be aligned vertically, in 2 different ways. Landscape and portrait can also be changed. There is no reason to add them to  "Fast options", although all of them are valid and many users may prefer one of them.
