### ISSUE TITLE
lxqt-config-brightness -i and -d don't work properly on AMD

### ISSUE THREAD

**Issue by gabrc52** [lxqt/lxqt-config#625]
##### Expected Behvior
lxqt-config-brightness adjusts the backlight of the display

##### Current Behavior
lxqt-config-brightness ignores the backlight of the display, and adds a transparent black filter to make it seem as if the brightness is being adjusted. Additionally, it prints:

    (0x7ffdf7975ba0) Debug: No outputs have backlight property

However, adjusting the slider does work as intended.

##### Possible Solution

Adjust the backlight brightness the same way it's adjusted when the slider is adjusted.

##### Steps to Reproduce (for bugs)
1. Use an AMD laptop
2. Run lxqt-config-brightness -d

##### Context
Lubuntu uses `lxqt-config-brightness -i` / `-d` to adjust the brightness when brightness keys are pressed.

##### System Information
* Distribution & Version: Ubuntu 20.04
* liblxqt Version: 0.14.1
* Package version: 0.14.1-0ubuntu3
**I did read the warning about Ubuntu, but I can't find that any evidence that this bug was fixed on the upstream version**

**Comment by tsujan** [comment]
The GUI has changed but I don't know about the command-line. @selairi ?

**Comment by selairi** [comment]
Commands can be replaced by:
`pkexec lxqt-backlight_backend --inc`
`pkexec lxqt-backlight_backend --dec`

I think that the problem with backlight was solved in:
[https://github.com/lxqt/lxqt-config/commit/1d9a6d37294cf20602c66abfe7377fc198e01867#diff-a6e693c2cb37386443355e0d8ccc9ca4](https://github.com/lxqt/lxqt-config/commit/1d9a6d37294cf20602c66abfe7377fc198e01867#diff-a6e693c2cb37386443355e0d8ccc9ca4)

**Comment by tsujan** [comment]
@selairi, thanks for the explanation.
