### ISSUE TITLE
"Single click to activate items" enables and disables libinput 'Tapping Enabled'

### ISSUE THREAD

**Issue by Bydo-Spore** [lxqt/lxqt-config#638]
Proof that "Single click to activate items" enables and disables libinput 'tapping enabled':

With "Single click to activate items" disabled:
```
xinput --list-props 12
...
libinput Tapping Enabled (302): 0
...
```

With "Single click to activate items" enabled:
```
xinput --list-props 12
...
libinput Tapping Enabled (302): 1
...
```

"Single click to activate items" has no other effect.

**Comment by tsujan** [comment]
There was no need to open another issue for https://github.com/lxqt/lxqt-config/issues/637. Closing an issue doesn't mean the discussion is over; issues can always be reopened. Please follow https://github.com/lxqt/lxqt-config/issues/637.
