### ISSUE TITLE
lxqt-config-monitor: 'Apply' Not Saving Current Configuration

### ISSUE THREAD

**Issue by Chiitoo** [lxqt/lxqt-config#642]
This might be more of a request for comments than an issue report, but in any case, before I put more time into (properly) changing things, I figured I'd make sure if changes would be appreciated or not.

##### Expected Behavior

Clicking 'Apply' in 'Monitor Settings' saves the current configuration as 'currentConfig' in 'lxqt-config-monitor.conf'.

##### Current Behavior

The current configuration is only saved when 'Save' is clicked.

##### Possible Solution

At first I thought this might be as simple as adding calls to whatever writes 'currentConfig' in at least one more place, but it seems it's done in 'MonitorSettingsDialog::saveConfiguration' (https://github.com/lxqt/lxqt-config/blob/master/lxqt-config-monitor/monitorsettingsdialog.cpp#L163), so without duplicating things it would not be quite that simple to do (or maybe it just needs a global variable, but I'm not sure how good of an idea that is).

So, I was wondering if the best way to handle this would be to refactor the writing of 'currentConfig' and 'SavedConfigs' out of 'saveConfiguration', or/and turn 'saveConfiguration' into something else.

##### Steps to Reproduce (for bugs)

1. Run 'lxqt-config-monitor'.
2. Change some settings.
3. Hit 'Apply'.
4. Observe 'currentConfig' not being written into 'lxqt-config-monitor.conf'.

##### Context

I bumped into this while using a dual monitor set-up with DisplayPorts involved.  DisplayPort seems to have this... "feature"... where it disappears completely as far as the machine is conserned when the monitor is powered off.  This lead into unexpected (to me at least) settings to be automagically selected whenever I turned it on again (the settings I had last saved, not the 'current' settings I had set just before powering the thing off).

##### System Information

* Distribution & Version: Gentoo Linux
* Kernel: Linux 5.8.7
* Qt Version: 5.15.1 (5.15 git master)
* liblxqt Version: 0.15.1 (git master)
* lxqt-build-tools Version: 0.7.0 (git master)
* Package version: 9999 (git master)

**Comment by tsujan** [comment]
When I was working with a dual monitor to fix bugs in some LXQt components and test them, I found the difference between `Apply` and `Save` very useful. With `Apply`, I could test settings that I didn't want to persist between sessions, while with `Save`, I could have a good setting after login.

You put it inside quotes but I think this is a really good *feature*. If it didn't exist, I'd make a PR for it.

**Comment by Chiitoo** [comment]
I did imagine it might indeed be desired behaviour to some, but to me it was unexpected, so here we are.  :]

The "feature" I was talking about, in quotes, is how the DisplayPort display disappears from the machine completely, or at least so far it seems to do so (according to a friend this also happens when using Windows).  This leads to some differences in behaviour when comparing to, for example, DVI or HDMI connections.

Thanks!

**Comment by tsujan** [comment]
I don't know about DisplayPort. If you think there's a problem related to the difference between `Apply` and `Save`, you could reopen this issue, or if the problem is somewhere else but inside `lxqt-config-monitor`, you could change the title before reopening or open another issue.

As for `lxqt-config-monitor`, I'm a user like you are. I just told about my experience as you did (without closing the report), thinking that a discussion might happen and it might lead to a different implementation.

**Comment by Chiitoo** [comment]
I'm thinking the DisplayPort issue is deeper within, possibly even at hardware level since there are similar issues with it in the Windows land too.  It's probably not something that should be fixed in LXQt.

I would definitely not mind this issue being open in case you think others might want to chime in (not that they still can't), but currently I'm quite fine with it as well, especially now that I know why I was getting a different saved configuration from what I was expecting.

The monitor settings probably could use some work all in all, at least regarding all the different Apply buttons that can be found there (there's already an open issue mentioning that though).

**Comment by tsujan** [comment]
I was thinking about changing the labels in this way: `Apply` → `OK`, `Save` → `Apply`, `Settings` → `Saved Settings`. But I'm not sure whether the changes would make things clearer or more confusing ;).
