### ISSUE TITLE
All Touchpad settings disabled

### ISSUE THREAD

**Issue by antis81** [lxqt/lxqt-config#644]
##### Expected Behavior

Ability to adjust touchpad properties.

##### Current Behavior

One Picture, less words. :)

![touchpad-config-disabled](https://user-images.githubusercontent.com/440517/93017692-f4f33580-f5ca-11ea-974c-bc05f708f044.png)

##### Possible Solution
Show warning when driver != "libinput".

##### Steps to Reproduce (for bugs)
1. Open lxqt-config-input
2. select touchpad settings

##### Context

Trying to customize Touchpad to my needs.

##### System Information
* Distribution & Version: Manjaro 20.1
* Kernel: 5.4 (LTS)
* Qt Version: 5.15
* liblxqt Version: 0.15.1
* lxqt-build-tools Version: ?? 
* Package version: 0.15.0

**Comment by tsujan** [comment]
@yan12125, any idea how that can happen? It hasn't happened for me with 2 laptops.

**Comment by antis81** [comment]
Meh… solved it by myself! :8ball: 

FYI:
lxqt-config-input expects "libinput" to be the driver setting.

In my case it was an "old" `xf86-input-synaptics` config file (/etc/X11/xorg.conf.d/30-touchpad.conf).
Unfortunately (German) web-searches still point to this in the Arch wiki: https://wiki.archlinux.de/title/wiki.archlinux.de:Synaptics_Touchpad_Treiber 

**Further deleting that file leads to same results (settings not editable).**

Here is the correct file (/etc/X11/xorg.conf.d/40-libinput.conf):

```
Section "InputClass"
    Identifier "Tuxedo1704 Touchpad"
    Driver "libinput" # <-- "synaptics" is unsupported
    MatchIsTouchpad "on"
    Option "Tapping" "on"
    Option "TappingButtonMap" "lrm"
    Option "ScrollMethod" "two-finger"
    Option "NaturalScrolling" "true"
EndSection```

Could lxqt-config-input fix itself maybe by simply hardcoding the driver? (libinput is the only one supported by LXQT)

**Comment by yan12125** [comment]
Maybe a warning below if no libinput configuration options are found for the current device.

**Comment by tsujan** [comment]
`libinput` is presupposed in most distros and is installed with a standard Manjaro installation (= the reporters's distro); so I thought it couldn't be the cause.

Adding a warning is good but I don't think it's urgent.

**Comment by antis81** [comment]
@tsujan Implementing such warning is a matter of minutes. Is it really worth a discussion about priorities?

**Comment by tsujan** [comment]
> Is it really worth a discussion about priorities?

If you have time to make a PR for it, no.

**Comment by antis81** [comment]
> If you have time to make a PR for it, no.

Sure, I will give it a go tonight or tomorrow morning… :smile:

**Comment by antis81** [comment]
FYI: If `xf86-input-synaptics` package is *not* installed xinit "automagically" implies libinput regardless of the xinit configuration. Not very "user friendly" IMHO, but hey it works. 

@yan12125 Could you give it a short review please? I decided to also add a minor fix for the double/float enum of "acceleration" property (QVariant does always store floating point values as double; therefore QVariant::Float type does not exist and QMetaType::Float is incorrect here).
