### ISSUE TITLE
More detailed color customization

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt-config#646]
The latest git LXQt can set the window color and Qt will calculate other colors based on it. But some users may want more customization.

The following screenshot shows my proposal:

![palette](https://user-images.githubusercontent.com/981076/94287559-53bd9500-ff63-11ea-8b85-fad211e8e315.png)

The page is a scroll area so that the new color labels don't make it bigger.

The number of colors Qt supports is much more than 6 but, IMHO, we don't need more. If the user wants a finer customization, he/she will need a widget style with separate options that can be used under all DEs.

I opened this page for discussion before implementation. If it's decided quickly, I'll implement it before 0.16; otherwise, it could wait.

EDIT: Link and visited link colors should also be added (see below).

**Comment by hmollercl** [comment]
nice! I think that amount is enough craziest thing I've seen is:
![image](https://user-images.githubusercontent.com/30954443/94301709-6e7f1200-ff41-11ea-9897-8767a99b8f26.png)
and the orange sliders and border in fm I believe it would be obtained with "selection".
I would think in storing that in a different .conf file only for the colors for easier "redistribution".

**Comment by tsujan** [comment]
@hmollercl 
Your screenshot showed me that I'd missed 2 colors: link and visited link. They should be added because the default isn't good with all backgrounds. Thanks!

So, there are 8 colors for now. Several lines of code should be added to `lxqt-qtplugin` and `lxqt-config`. I'll test them tomorrow.

**Comment by tsujan** [comment]
After the above-mentioned change, it'll be like this (with Fusion):

![palette_fusion](https://user-images.githubusercontent.com/981076/94305837-b8d2b400-ff7e-11ea-8218-ca35bc43f37a.png)

**Comment by tsujan** [comment]
Please note that:

 1. The disabled colors are derived from enabled ones. So, there will be a small difference between LXQt's default and Fusion's colors but only in disabled widgets.
 2. Inactiveness is ignored. In Fusion, active and inactive colors are the same and most users don't know about inactiveness other than in title-bars (which isn't our concern). 16 colors would be an overkill, IMO.

**Comment by tsujan** [comment]
Update:

It's finished and works fine. Will make 2 PRs tomorrow.

Unfortunately, Breeze still needs KDE's System Settings for a few colors (selected menu-item and focus rectangles). Nothing can be done for it. That's a design flaw in Breeze: it depends on 2 non-Qt colors of KDE Color Scheme (focus and hover "decoration" colors).

**Comment by tsujan** [comment]
The PRs are https://github.com/lxqt/lxqt-qtplugin/pull/61 and https://github.com/lxqt/lxqt-config/pull/647, the latter needing the former.

I added a "Default Palette" button too, for restoring Fusion colors. The GUI is like this now:

![palette_last](https://user-images.githubusercontent.com/981076/94343282-e7569a80-0023-11eb-9cea-73bd58c12e72.png)

**Comment by hmollercl** [comment]
Just tested and it works ok for me.
My only comments are:
- I would safe the palette colors in a different .conf file rather than the same lxqt.conf (palette.conf for instance) for easy share of palettes.
- I would made 2 column for colors so it wouldn't be so high, like:
window | window text
view | view text
selection | selected text
link | visited link

**Comment by tsujan** [comment]
> Just tested and it works ok for me.

I appreciate your test. Thanks!

> I would safe the palette colors in a different .conf file

I understand your argument but that file is watched by the code, so that if you manually edit it, the changes will apply. I don't think it's a good idea to watch 2 files.

> I would made 2 column for colors

I agree; it'll be better both visually and logically. I may make the required changes to the PR.

**Comment by tsujan** [comment]
Done in https://github.com/lxqt/lxqt-config/pull/647/commits/cf36071355d1930ac334ebbe953d29e0b38cc3f3:

![two_columns](https://user-images.githubusercontent.com/981076/94976739-c5c54980-0522-11eb-99c2-ed47c30978f6.png)

**Comment by hmollercl** [comment]
Love it!
![image](https://user-images.githubusercontent.com/30954443/94995493-ffbf3b80-0574-11eb-8387-2bdf940bb0c4.png)

**Comment by stefonarch** [comment]
Just testing this, works fine! 
 I'd only increase slightly default window size to ca. 700x550 to avoid both scrollbars:
![schermata-17-23-27-44](https://user-images.githubusercontent.com/10681413/96353877-680f3080-10d0-11eb-9d0e-9f61380c3ae5.png)

**Comment by tsujan** [comment]
@stefonarch 
The scrollbars depend on text size and other factors; they can't be removed for all users. But I have a plan to make all lxqt-config dialogs remember their sizes. Will try to make a PR before 0.16.0.

**Comment by stefonarch** [comment]
Good, because it seems that many windows are still designed for 800x600... but I'd increase their default size too.

**Comment by tsujan** [comment]
> Good, because it seems that many windows are still designed for 800x600

Yes :) And yet, last year, we had reports about too big windows! VirtualBox without guest additions?...

Anyhow, size remembering will solve this problem. Will make a simple PR today.

**Comment by tsujan** [comment]
Done in https://github.com/lxqt/lxqt-config/pull/654
