### ISSUE TITLE
[lxqt-config-appearance] - Add in Openbox theme selector? (may partially deprecate obconf-qt?)

### ISSUE THREAD

**Issue by AzumaHazuki** [lxqt/lxqt-config#648]
This is just an idea, as I'm aware LXQt doesn't hard-depend on or lock its users into Openbox. Would it be possible, or even advisable, to add in an "Openbox Theme" section to the Appearance configurator?

I've attached a very quick and dirty mockup I made in The GIMP of what this might look like. Basically it would just add another item and icon to the left panel and reproduce the theme list from obconf-qt in the right panel.
![LXQt-Appearance-Mockup](https://user-images.githubusercontent.com/67122280/94585621-44359900-024e-11eb-9b5e-9dbbb646c05b.png)

**Comment by tsujan** [comment]
As you correctly implied, neither Openbox nor any other WM is an integrated part of LXQt (that might change with Wayland at some point), although several WMs can be used with LXQt. On the other hand, `lxqt-config-appearance` is about LXQt. Adding a section for the settings of a WM would contradict those facts.
