### ISSUE TITLE
LXQt Appearance doesn't find GTK themes which installed to ~/.themes

### ISSUE THREAD

**Issue by zoli111** [lxqt/lxqt-config#665]
##### Steps to Reproduce
1. Put a GTK theme to ~/.themes folder
2. Open Appearance Settings. The name of the theme doesn't appear in the combo list. This happens both with GTK2 and GTK3 themes.

##### System Information
* Distribution & Version:  Arch
* Kernel: 5.9.1-arch1-1
* Qt Version: 5.15.1-3
* liblxqt Version: 0.15.1.10.g8669419-1
* lxqt-build-tools Version: 0.7.0.3.g905b1e3-1
* Package version: 0.15.0.75.g27ae877-1

**Comment by tsujan** [comment]
The `~/.themes ` folder is obsolete. Have you tried `~/.local/share/themes`?

**Comment by zoli111** [comment]
It works with the other path. Thank you!

**Comment by tsujan** [comment]
Yes, I tried it and it worked. But, here, I see a strange and unrelated issue: in the gtk2 list, there is an item with ".." as its text. I hadn't seen it before.

**Comment by tsujan** [comment]
Found the cause of the above-mentioned issue: the directory filter in `configothertoolkits.cpp` → `ConfigOtherToolKits::getGTKThemes()` should be `QDir::Dirs | QDir::NoDotAndDotDot`, not `QDir::Dirs`.

It's too late to fix it; 0.16.0 will come soon. I'll make a PR after 0.16.0.
