### ISSUE TITLE
multiple lxqt-config-monitor processes

### ISSUE THREAD

**Issue by tenplus1** [lxqt/lxqt-config#745]
When screen blanks after a set time, after a while when unblanking screen the process list contains multiple (up to 20 at one point) lxqt-config-monitor processes which had to be killed with a sudo killall to remove.

I'm using latest Lubuntu 21.04 release with AMD graphics.

Screenshot: https://imgur.com/a/0pKaZlK

**Comment by tsujan** [comment]
Not reproducible.

lxqt-config-monitor is a single-instance app and has nothing to do with screen blanking. Something may be wrong with your installation. Report it to your distro, Ubuntu.

When you report an LXQt issue here, please include the version of the app. "Lubuntu 21.04" is not related to upstream.
