### ISSUE TITLE
Cleanup Settings Menu and Configuration Center

### ISSUE THREAD

**Issue by antis81** [lxqt/lxqt-config#759]
##### Expected Behavior

1. Hover/Highlight on "start-menu -> settings" shows an alphabetically sorted list of all(!) settings   
1. Click on "start-menu -> settings" opens `LXQt Configuration Center`
1. All settings are listed in alphabetical order (me don't like sub-categories, but maybe an option)
1. third-party settings (such as KDE systemsettings, obconf-qt, Manjaro settings, …) should also appear as a selecable icon in `LXQt Configuration Center` frontend.

##### Current Behavior
1. Hover/Highlight on "start-menu -> settings" shows an alphabetically list of settings with `LXQt Settings` as a submenu (making it appear cluttered)
1. Click on "start-menu -> settings" has no effect
1. All settings are listed in alphabetical order (me don't like sub-categories, but maybe an option)
1. third-party settings are not shown at all in LXQt configuration center (except obconf-qt)

##### Possible Solution

<Screenshots/Mockup TBD>

##### Steps to Reproduce (for bugs)
Open "start-menu -> settings" (and submenus).

##### Context
Usability

##### System Information
* Distribution & Version: Manjaro (Pahvo)
* Package version: 0.17

**Comment by tsujan** [comment]
I'm afraid these are ideas and suggestions — neither feature requests nor bug reports— and some of them (e.g., third-party settings) are based on wrong assumptions. Please use https://github.com/lxqt/lxqt/discussions to discuss ideas. GitHub doesn't allow converting this report to a discussion.

**Comment by stefonarch** [comment]
>" * Click on "start-menu -> settings" opens `LXQt Configuration Center`

Cannot reproduce this neither in Lubuntu nor in git.

**Comment by tsujan** [comment]
@stefonarch 
I think he *prefers* that clicking on Start Menu would open LXQt Configuration Center — a strange thing indeed.

As for Configuration Center, it's first section is and should be about LXQt and nothing else. Its System Settings section contains the "System" category. It's self-consistent. What appears there depends on the value of the `Categories` key in a desktop file. It shouldn't be cluttered by every config tool.

Anyway, I think here isn't the right place for discussions.

**Comment by stefonarch** [comment]
Just as note I see that in the screen here https://github.com/lxqt/lxqt-config#configuration-center "users&groups" were shown in "system" where they belong, while now there are in  LXQt settings.

> I think he _prefers_ that clicking on Start Menu → Settings would open LXQt Configuration Center — a strange thing indeed.

Yes, I read it the other way round...

**Comment by tsujan** [comment]
> Just as note I see that in the screen here...

It's old. The desktop file of "Users and Groups" includes:
```
Categories=LXQt;Settings;DesktopSettings;Qt;
```
So, it appears in the first section.

I think the only app that doesn't belong to that section but appears there is Kvantum Manager. That's intentional and I did it years ago in response to a feature request. Its `Categories` shows the reason:
```
Categories=Qt;Utility;Settings;DesktopSettings;LXQt;X-XFCE-SettingsDialog;X-XFCE-PersonalSettings;X-GNOME-PersonalSettings;
```

**Comment by stefonarch** [comment]
So there was a change in the desktop file of lxqt-admin at some point. IMHO it's wrong as it is a system setting.

obconf-qt appears in  LXQt too, but its .desktop file doesn't include LXQt, didn't find out why.

`Categories=Qt;Settings;DesktopSettings;`

Even with only ` Categories=Settings;` its shown under LXQt

**Comment by tsujan** [comment]
> obconf-qt appears in LXQt too, but its .desktop file doesn't include LXQt,...

And the same for pcmanfm-qt's desktop settings dialog (and a few others). They have been enforced by `/etc/xdg/menus/lxqt-config.menu`.

**Comment by stefonarch** [comment]
Maybe this should be documented more precisely in the [README.md ](https://github.com/lxqt/lxqt-config#configuration-center).

**Comment by stefonarch** [comment]
I think something should be done.

* Not enforce anymore compton-conf and obconf-qt to show up under LXQt settings - consequent WM agnosticism
* "User and Groups" should be displayed under system and not LXQt. Some people use this under KDE too, as there is (or was)  no tool for user managment
* As discussed years ago, lxqt-about could be elsewhere 
* Show Configuration Center in main menu

I only discovered yesterday https://github.com/lxqt/lxqt-kcm-integration. With custom desktop files also for xfwm it's less confusing when more than one WM is installed.
![schermata-08-28-18-09-01](https://user-images.githubusercontent.com/10681413/131223984-45a22d6f-e900-4b0c-a55a-d0c27404e5f4.png)


![schermata-08-28-14-43-01](https://user-images.githubusercontent.com/10681413/131223986-5f9f6329-02f6-4cbe-b465-ea78f62bd58a.png)

One  option could be simply providing more types of lxqt-application-menus, documenting this.

**Comment by tsujan** [comment]
> Not enforce anymore compton-conf and obconf-qt...

I agree.

> "User and Groups" should be displayed under system and not LXQt.

I think its place was decided; don't know when or where.

> As discussed years ago, lxqt-about could be elsewhere

I don't install it ;) Will have no objection to any decision that might be taken.

> Show Configuration Center in main menu

IMHO, its current place is good.

**Comment by stefonarch** [comment]
> > Show Configuration Center in main menu
> 
> IMHO, its current place is good.

IMHO  it's too many levels away. What about a second menu file then, leaving the choice?

**Comment by tsujan** [comment]
I think it's just a matter of taste. I like it when I see all LXQt settings are in one sub-menu; it's neat. Contrary to most DEs, our main menu is a real menu; we don't need extra clicks to reach a sub-menu.

But I'll have no objection if LXQt members prefer another place.

**Comment by stefonarch** [comment]
> I see that `OnlyShowIn=KDE;` in systemsettings doesn't seem to work as it's shown

I see that KDE ships two .desktop files: one with `OnlyShowIn=KDE;` and the other with `NotShowIn=KDE;`, the latter is explicit about KDE settings. Smart.

**Comment by tsujan** [comment]
I don't remember it clearly and haven't dig into the sources but I think some keys aren't implemented yet; `OnlyShowIn` may be related to them. Alf mentioned them somewhere. It'll be nice if they're found and a report is made for them in the right place.

**Comment by stefonarch** [comment]
Here it's working. Look at ` /usr/share/applications/kdesystemsettings.desktop` and 
` /usr/share/applications/systemsettings.desktop`. There was an issue but I don't remember if it's fixed.

**Comment by tsujan** [comment]
Yes, but I'm sure that Alf mentioned a key that didn't work; a needle in a haystack....

**Comment by stefonarch** [comment]
A 2-Panel menu with Configuration Center:
![schermata-08-29-18-03](https://user-images.githubusercontent.com/10681413/131257164-e8977879-8784-47ed-a543-4e9b5c5e8be1.png)

Todo: a 2-Panel menu without Center but "Preferences" and LXQt Preferences".

**Comment by stefonarch** [comment]
> Yes, but I'm sure that Alf mentioned a key that didn't work; a needle in a haystack....

https://github.com/lxqt/lxqt/issues/1743
Still true.

**Comment by tsujan** [comment]
> Still true, but NotShowIn=LXQt

@stefonarch, you found it! Yes, that's the issue I was talking about.
