### ISSUE TITLE
Control Center doesn't display everything

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-config#761]
##### Expected Behavior

All items present in Mainmenu > Preferences are also displayed in LXQt Control Center.
##### Current Behavior

Some are missing: kde-systemsettings,ibus settings, advanced network configuration and else
##### Possible Solution

Fix `/etc/menus/lxqt-config.menu` which has a menu for "others" which is
* never displayed (apparently not working)
* refers to an inexistent `lxqt-settings-other.directory` file - existing is only` lxde-others.directory`
The name should also be more explicit: lxqt-control-center.menu as it's possibile to chose it in mainmenu settings and doesn't give a good UX.

##### Context

Control Center could be the only configuration tool in a menu, but this has to be fixed.
##### System Information

* Distribution & Version: all recent

**Comment by tsujan** [comment]
I ask these questions from myself: lxqt-panel is an app; why should the settings of one of its widgets be in Control Center? Do you really want to clutter Control Center with every setting we find? Why should we put all config tools in it, while the main menu has sections for them?...

**Comment by tsujan** [comment]
> Fix /etc/menus/lxqt-config.menu which has a menu for "others"

"Others" is shown here.

**Comment by stefonarch** [comment]
I've never seen it, neither in installations nor in VM's as I remember.
What do you have in "others"? Are ibus settings and im-config visible there?

> Do you really want to clutter Control Center with every setting we find? Why should we put all config tools in it, while the main menu has sections for them?

When we have something called "Configuration Center" it should be complete. And cluttering is not an issue IMHO, with three sections. As said in https://github.com/lxqt/lxqt-config/issues/759#issuecomment-907817973, I'd like to offer more menu files to chose from, one would have only the configuration center but it needs to be complete.

Draft:

![schermata-08-30-17-10](https://user-images.githubusercontent.com/10681413/131362123-034893e0-3b5a-4059-bc6f-3d136e3effdf.png)

**Comment by tsujan** [comment]
> What do you have in "others"?

I'll check later. It's in my other computer, where I have lots of garbage. "Others" is usually for garbage ;)

> When we have something called "Configuration Center" it should be complete.

It's *LXQt's* config center plus system settings. Why, for example, should we have KDE's system settings there? That would mislead users: they change font settings in KDE's settings and see no change in LXQt. Seeing KDE's keyboard shortcuts there is even worse.

**Comment by tsujan** [comment]
> Users which have installed it see kde-systemsettings already in the first panel of the "preferences"...

Yes, but by not seeing it in LXQt Configuration Center, they may guess it's alien.

The main menu should show everything that's supposed to be shown. What I'm saying is that I see no reason to duplicate a part of its job in Control Center.

**Comment by tsujan** [comment]
Let me put it in perspective:

In MS Windows, Control Center (or whatever its name is) includes almost everything because MS Windows doesn't know about concepts like DE, WM, Compositor, etc.: there's only one for each.

Some Linux DEs (like Gnome) may imitate MS Windows and pretend that everything is what they offer. Of course, old users Linux users aren't deceived but there are many Windows refugees.

LXQt has no claim in that regard. We say to our users that they can use whatever they want — Qt or GTK isn't important.

**Comment by stefonarch** [comment]
> What I'm saying is that I see no reason to duplicate a part of its job in Control Center.

 Talking about duplicating: I see no reason to duplicate only a part of all preferences in  the control center - and I see  no reason to have such a thing in the menu when already all  preferences are well accessible in the menu. 

A similar thing is true for leave > leave which shows again even lockscreen. It's ok to have a full menu, but I think it's also ok to have only ab essential menu or more of them without any duplicates.
