### ISSUE TITLE
Keyboard layouts not remembered after session restart

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-config#765]
Actually not sure when this happened, if related to https://github.com/lxqt/lxqt-globalkeys/commit/55e0231ea16f8580aed7ae7054a47aa7c4691575 or to my heavy kwin experiments some days ago. Same issue on a  fresh user.  `globalshortcuts.conf` gets updated when reconfiguring but shows no diff.

##### Expected Behavior

Layouts (here 2) are remembered,
##### Current Behavior

They are not, defaults to main locale (it), only shortcut is remembered.
##### Steps to Reproduce (for bugs)

1. Add a second language in plugin kbindindicator.
2. Logout/login
3. Second language is disappeared.

* Distribution & Version: latest git, debian bullseye

**Comment by tsujan** [comment]
What if you choose another layout; for example, German or French?

**Comment by tsujan** [comment]
Another question: Doesn't layout change by clicking the Keyboard State Indicator on Panel either?

**Comment by stefonarch** [comment]
Tested, the config file reflects it, on session restart always only "it", while session.conf has still all three I set before.
Will rebuild anything tomorrow, it has to be at system level somewhere.

No change in clicking nor with shortcut, that's how I noticed it because I switch several times a day.

**Comment by stefonarch** [comment]
Rebuilded lxqt-session and lxqt-config, no change.
![schermata-09-04-23-24-01](https://user-images.githubusercontent.com/10681413/132108415-ed34676d-03de-4595-971e-a62933ce0874.png)

**Comment by tsujan** [comment]
lxqt-config's input hasn't changed since the last release. The problem should be somewhere else. I don't know where but we could try to find relevant programs and check them one by one.

**Comment by tsujan** [comment]
> I helped me atm with setxkmap it,ch at login

`lxqt-config` uses it too: https://github.com/lxqt/lxqt-config/blob/2d267c505c469b22865546ffcc268b85982c1afb/lxqt-config-input/keyboardlayoutconfig.cpp#L222

**Comment by tsujan** [comment]
I think, in your case, some program may override setting of keyboard layout by LXQt. The first thing I'd do would be checking all apps that are started with LXQt Session and seeing if one of them can set the keyboard layout.

KDE may add useless startup apps; I've disabled them here.

**Comment by stefonarch** [comment]
I ended up with the same idea and found the reason: or ibus or im-config which I added again to test something.

**Comment by tsujan** [comment]
I'd heard that ibus can do that under Gnome too.
