### ISSUE TITLE
Installing filelight will become the default file manager

### ISSUE THREAD

**Issue by chomwitt** [lxqt/lxqt-config#767]
##### Expected Behavior
I expect PCMan to open when some applications (eg: calibre,hexchat) contain 'buttons' to see some folders. 

##### Current Behavior
After installing filelight binary deb package 4:20.12.0-1 corresponding to
fileligth version 20.12.0 filelight will be set as default file manager as
i can see from  Desktop main menu / LXQtsettings/FileAssociations/DefaultApplications
and also applications like the two examples i mentioned behave as if filelight
is a file manager and open it when i click on relevant buttons .

##### Possible Solution
Set again PCMan as the default file manager from
Desktop main menu / LXQtsettings/FileAssociations/DefaultApplications

##### Steps to Reproduce (for bugs)
Having checked that ~/.config/lxqt-mimeapps.list
~/.config/mimeapps.list dont contain any inode/directory entries
we $ sudo apt-get install filelight

##### System Information
 * Distribution & Version: Devuan Chimaera 
* Kernel:  5.10.0-7-amd64 x86_64
* LXQt Version: 0.16.0

**Comment by tsujan** [comment]
Please upgrade to the latest version (0.17 for now). Also, you could follow https://github.com/lxqt/lxqt-panel/issues/1661

**Comment by tsujan** [comment]
Your old version probably doesn't have this:

![file_manager](https://user-images.githubusercontent.com/981076/132969511-e298c17d-b457-4d41-bd5b-1306474086ce.png)

**Comment by chomwitt** [comment]
Indeed my version dont have that look ,  but it has the same content.
![lxqt-defaults](https://user-images.githubusercontent.com/1383580/133001891-c1b95d06-9b91-4e5b-8911-ba6aee7f62bd.png)

**Comment by tsujan** [comment]
> but it has the same content.

It's the same (the look is about Qt style). Then I should have added it before 0.16. Sorry, sometimes I don't remember what was in old versions.

Anyway, you can find your answer [here](https://github.com/lxqt/lxqt-panel/issues/1661#issuecomment-917684056) (first paragraph) and [here](https://github.com/lxqt/lxqt-panel/issues/1661#issuecomment-917693451).
