### ISSUE TITLE
[Feature Request] Default dark palette

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-config#771]
Add  a second button for  "default dark palette" in lxqt-config-appearance.

##### Current Behavior

Setting a dark palette needs many clicks atm, switching from dark to bright theming and back would be easier.
##### Possible Solution

As above

##### Context

In theme testing it's annoying always to set at least 4 colours by hand.

**Comment by tsujan** [comment]
Won't it be better if we add a way of saving/restoring user-defined palettes instead?

**Comment by stefonarch** [comment]
Hm, why not both?  :)
But for first time users of palette a dark default one would be good IMHO, so users can easily switch. 
Not sure but could the dark palette be triggered also be selecting dark themes in some way?

**Comment by tsujan** [comment]
> why not both?

Because making a dark palette is a piece of cake and the second functionality makes the first one redundant. Moreover, there's really no default dark palette in Qt, while Qt does have a default palette, which is light.

**Comment by tsujan** [comment]
> Not sure but could the dark palette be triggered also be selecting dark themes in some way?

You mean LXQt (panel) themes. They're in QSS, which is at odds with QStyle. We can't know if an LXQt theme is light or dark.

But, if palettes are saveable and restorable, palettes with the same names could be added and applied.

**Comment by stefonarch** [comment]
> But, if palettes are saveable and restorable, palettes with the same names could be added and applied.

That sounds good, and there would be any kind of palette then?

> > why not both?
> 
> Because making a dark palette is a piece of cake and the second functionality makes the first one redundant. Moreover, there's really no default dark palette in Qt, while Qt does have a default palette, which is light.

Right, I don't have those insights in Qt.

**Comment by tsujan** [comment]
> and there would be any kind of palette then?

Why not? We could add palettes corresponding to our LXQt themes, and more.

Its logic is simple: like KDE color schemes but without style-specific components. The implementation will take time but I'm quite motivated (although I won't use this feature -- I use Kvantum, which is independent of palettes).

**Comment by tsujan** [comment]
This is what I mean:

![palettes](https://user-images.githubusercontent.com/981076/135751643-b972cc59-4325-4b86-be30-a395c2bda114.png)

When "Save Palette" is clicked, this dialog will appear:

![save_palette](https://user-images.githubusercontent.com/981076/135751660-d3ac065a-ca2f-4829-8044-bf014067d512.png)

And this one shows up if "Load Palette" is clicked and there are palettes:

![load_palette](https://user-images.githubusercontent.com/981076/135752020-98aa248c-037d-4199-8cc2-079b0d054030.png)

If there's no palette, the user will be informed by this:

![no_palette](https://user-images.githubusercontent.com/981076/135751717-66a11cc2-e182-4fc2-8117-b5cd1dd5b014.png)

Palettes are saved in `~/config//lxqt/palettes` and loaded from the `palettes` directories in all generic config and data locations.

**Comment by stefonarch** [comment]
I had some sensation that you were working on that, and I was right :)
It looks quite perfect for all needs IMHO

**Comment by tsujan** [comment]
It was easy up to this point. The rest is somehow complicated and needs more care. For example, user palettes should have priority over root palettes; or if the user removes a palette and a root palette with the same name exists, the user should be informed about that (because root palettes can't be removed); etc.

So, it'll take some time. But I'll try to make it ready before the next release.

**Comment by tsujan** [comment]
Didn't see a reason to wait; its logic was simple. The PR is https://github.com/lxqt/lxqt-config/pull/772 and needs to be tested.
