### ISSUE TITLE
Lack of proper build instructions

### ISSUE THREAD

**Issue by J-Dunn** [lxqt/lxqt-config#787]
README.md says:

```
Compiling source code

Runtime dependencies are Xcursor, qtsvg, KScreen and liblxqt. Additional build dependencies are CMake and optionally Git to pull latest VCS checkouts.

Code configuration is handled by CMake. CMake variable CMAKE_INSTALL_PREFIX has to be set to /usr on most operating systems, depending on the way library paths are dealt with on 64bit systems variables like CMAKE_INSTALL_LIBDIR may have to be set as well.

To build run make, to install make install which accepts variable DESTDIR as usual.

```
After unpacking the tar.gz and adding a build directory, running cmake fails. 

```
bash-5.1#CMAKE_INSTALL_PREFIX=/usr; cmake -S . -B ./build
CMake Error at CMakeLists.txt:38 (find_package):
  By not providing "Findlxqt.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "lxqt", but
  CMake did not find one.

  Could not find a package configuration file provided by "lxqt" (requested
  version 0.16.0) with any of the following names:

    lxqtConfig.cmake
    lxqt-config.cmake

  Add the installation prefix of "lxqt" to CMAKE_PREFIX_PATH or set
  "lxqt_DIR" to a directory containing one of the above files.  If "lxqt"
  provides a separate development package or SDK, be sure it has been
  installed.
```

(requested version 0.16.0) ?? Why is this "requested" in 0.16.1 source code? 

What is missing here? Where are accurate build instructions? 
Thanks.

**Comment by stefonarch** [comment]
At least the first four are needed: https://github.com/lxqt/lxqt/wiki/Building-from-source#compiling
The readme should mention those.

**Comment by J-Dunn** [comment]
Many thanks.  I already had the qt5 and cmake stuff from building another project from src.  I added the "miscellaneous" pkgs from just above where your link pointed to. 

None of that actually looks relevant to the errors I was getting and the same errors still come up when I run cmake 
`CMAKE_INSTALL_PREFIX=/usr; cmake -S . -B ./build
`

> or set  "lxqt_DIR" to a directory containing one of the above files.

Those files are not present in the tar ball. There seems to be something amiss here. Is the tarball complete, does it have a version number error, seen above ?

**Comment by palinek** [comment]
> Many thanks. I was missing lxqt-build-tools.

> Those files are not present in the tar ball. There seems to be something amiss here.

You need all from the previous levels, not just lxqt-build-tools.

> CMAKE_INSTALL_PREFIX=/usr

If I were you, I would not mess the system this way. Use something in your $HOME and get familiar with the result and optionally use CMAKE_PREFIX_PATH also.

**Comment by rubyFeedback** [comment]
I have had a similar issue.

My current compile chain is specified as this:

    lxqt:
    - lxqtbuildtools          # clxqt1
    - libsysstat              # clxqt2
    - qtermwidget             # clxqt3
    - libqtxdg                # clxqt4
    # - comptonconf           # ------ # This has been deprecated.
    - lxqtconfig              # clxqt5
    - liblxqt                 # clxqt6
    - lxqtabout               # clxqt7
    - lxqtadmin               # clxqt8
    - lxqtglobalkeys          # clxqt9
    - lxqtl10n                # clxqt10
    - lxqtnotificationd       # clxqt11
    - lxqtopensshaskpass      # clxqt12
    - lxqtpanel               # clxqt13
    - lxqtpolicykit           # clxqt14
    - lxqtpowermanagement     # clxqt15
    - lxqtqtplugin            # clxqt16
    - lxqtrunner              # clxqt17
    - lxqtsession             # clxqt18
    - lxqtsudo                # clxqt19
    - lxqtthemes              # clxqt20
    - libfmqt                 # clxqt22
    - pcmanfmqt               # clxqt23
    - lximageqt               # clxqt24
    - obconfqt                # clxqt25
    - pavucontrolqt           # clxqt26
    - qterminal               # clxqt27
    - qps                     # clxqt29
    - screengrab              # clxqt30
    - lxqtarchiver            # clxqt31

As you can see this is a bit old; comptonconf is no longer available for
instance. As far as I know nobody specified the compile chain, and
what makes this even more confusing is that it's not trivial to differ
between the names. See my other issue report of "lxqt-config
can not find lxqt-config.cmake", which is just sooooo confusing.

I understand this is not necessarily all the fault of the lxqt devs, 
since cmake also factors in, but nonetheless for me as someone
trying to compile stuff from source I run into issues that are just
confusing. I can compile gcc, glibc, the linux kernel, all of qt 
and kde (well ... I currently have an issue with kio, but this is
not related to lxqt). Any improvement to the build setup would
be greatly appreciated. It's not a new issue for me either, I
have had problems with the lxqt-compile chain in the past. 
Whereas with mate-desktop and xfce everything works really
well. Nobody likes GNU configure anymore (I understand that
too), but cmake also has some issues.

**Comment by stefonarch** [comment]
The build order is [well documented](https://github.com/lxqt/lxqt/wiki/Building-from-source#generalbuild-order). You build liblxqt too late.

I don't know if we really should add a link to this in each and every components README.

**Comment by J-Dunn** [comment]
If you have such zany and specific build requirements, they should be included where ever they are a needed. 
The whole point of a README is to cover stuff like that. It's the point of reference. 
It's not "well documented" if you don't get told where the doc is. ;)

**Comment by tsujan** [comment]
I think this can be closed. All the needed info is already available to those who are familiar with building. Teaching how to build can't be LXQt's job.

**Comment by stefonarch** [comment]
One step, if you go up the tree  you'll find all 4 build components needed.

**Comment by J-Dunn** [comment]
Thanks for adding the wiki referenec to the README, that will be helpful.
