### ISSUE TITLE
Remove entirely the dependence on KWindowSystem ?

### ISSUE THREAD

**Issue by AdelKS** [lxqt/lxqt-config#800]
Hello! 

We are in the process of [bundling LXQt 1.0.0 within Gentoo](https://github.com/gentoo/gentoo/pull/22845) and it seems that you didn't remove entirely the dependence on `KF5WindowSystem` as it is still referred to [in other config files](https://github.com/gentoo/gentoo/pull/22845#issuecomment-991417573), is this intended ?

Adel

**Comment by tsujan** [comment]
Indeed, `lxqt-config` seems to be independent of KF5. Thanks!

**Comment by luis-pereira** [comment]
@AdelKS liblxqt actually depends on KF5 KWindowSystem.

**Comment by AdelKS** [comment]
thanks @luis-pereira @tsujan
