### ISSUE TITLE
[Bug] Color is not applied to breeze

### ISSUE THREAD

**Issue by libalis** [lxqt/lxqt-config#812]
![LXQt-Config](https://user-images.githubusercontent.com/45124869/154598445-ad5b998b-0ba1-4821-958c-8be725ed2f52.png)
As you can see on the screenshot, the color settings that work under fusion are not applied correctly under breeze.

##### System Information
PCManFM-Qt version: 1.0.0
Distribution & Version: openSUSE Tumbleweed
Qt Version: 5.15
liblxqt Version: 1.0.0

**Comment by stefonarch** [comment]
Does application restart or relogin fix it?
If not it's a duplicate of https://github.com/lxqt/lxqt/issues/2192

**Comment by libalis** [comment]
Restarting does not fix it, either breeze ignores it or lxqt does not set a breeze specific color.

**Comment by libalis** [comment]
I agree, but it would still be interesting to know what causes this issue.

**Comment by tsujan** [comment]
Please follow https://github.com/lxqt/lxqt/issues/2192

It has happened only recently. Whether it's related to a change in Breeze or caused by a problem in virtual machines, we still don't know.

**Comment by stefonarch** [comment]
> or caused by a problem in virtual machines

It's on my real laptop, in VM it gets fixed on restart apps or session.
