### ISSUE TITLE
Separate page for GTK settings

### ISSUE THREAD

**Issue by ianfarrell47** [lxqt/lxqt-config#817]
Currently in lxqt-config-appearance there is a scrollbar on small resolutions for the sub-pane "Widget Style".

Perhaps GTK styling could be moved to it's own sub-pane? Whatever could be done, I believe there is too many things in the "Widget Style" sub-pane currently.

This would help users of screens with resolution e.g. 1366x768.

**Comment by stefonarch** [comment]
We did a similar thing with the panel config menu already.
https://lxqt-project.org/blog/2022/02/14/lxqt-1.1.0-preview/

There was a discussion about the whole lxqt-config-appearance window elements and some reordering, I cannot find it atm. Because gtk settings apply also fonts and that is not clear.


gtk.integration in dedicated subpane could be a solution.

**Comment by tsujan** [comment]
> We did a similar thing with the panel config menu already.

This is different. GTK theme is the non-native part of "Widget Style" and, IMO, should remain there. Scrollbars exist to be used when needed.

That being said, we can make the "Widget Style" page tabbed and move the GTK theme settings to the second tab.

**Comment by stefonarch** [comment]
But widget style isn't about fonts, and gtk integration does this too.

**Comment by tsujan** [comment]
> But widget style isn't about fonts, and gtk integration does this too

GTK icons too. That's unfortunate. (I don't use this section; have set `~/.config/gtk-3.0/settings.ini` manually and once for all.)

OK, you're right, a separate section may be better — as the last section, because it's non-native.

**Comment by tsujan** [comment]
I started to do it. Self-assigning...

**Comment by tsujan** [comment]
This is much cleaner, both in the GUI and in the code:

![appearance1](https://user-images.githubusercontent.com/981076/157632729-55444c6f-fb3e-4cc4-b8aa-7a1e53af0acf.png)

![appearance2](https://user-images.githubusercontent.com/981076/157632756-7be4427b-6100-4181-9959-8c6177134f55.png)

**Comment by stefonarch** [comment]
Looks good! There is still [this issue](https://github.com/lxqt/lxqt/issues/658) I remember now.

**Comment by tsujan** [comment]
> There is still https://github.com/lxqt/lxqt/issues/658 I remember now.

I remember it was discussed elsewhere too, an my opinion was that it was good to have it in two places. I still have the same opinion because it's needed in both GUIs. But let's not discuss it here.

**Comment by ianfarrell47** [comment]
Amazing work tsujan. I'm just curious - who approves merge requests? I am beginning to learn Git and I already know some C++ (mainly just C a.t.m.). I'd love to do more than just create layman's issues.

**Comment by tsujan** [comment]
> I'd love to do more than just create layman's issues.

PRs by contributors are very welcome.

> who approves merge requests?

LXQt devs.
