### ISSUE TITLE
Remember the size of lxqt-config-input dialog

### ISSUE THREAD

**Issue by ianfarrell47** [lxqt/lxqt-config#820]
##### Issue
The default dimensions of lxqt-config-input's GUI should include more room for the page pane.
This is the dimensions that lxqt-config-input starts with:
![157998378-41415f0a-516d-4e42-b6d8-13c3105b6f54](https://user-images.githubusercontent.com/96850319/158002469-f29bd9d6-567e-4013-a02b-990501977196.png)

All pages fit well in the minimum dimensions  already, this would only increase the size so they have more room.

##### Possible solution
Increase minimum size of window to include more room. If DPI changes things too large, allow for scrollbar.

##### Drawbacks to solution
Code complexity and bigger dimensions on launch

##### System Information
lxqt-config-git - 1.0.0.25.g5ab3a64-1 5ab3a64
liblxqt - 1.0.0-1
lxqt-qtplugin - 1.0.0-2
qt5-base - 5.15.3+kde+r133-1
Qt5 style: Fusion
Font: 12 Noto Sans Display
linux 5.15.27-1-lts

**Comment by tsujan** [comment]
There's no reason to give more width to the left pane. The width is calculated correctly.

**Comment by tsujan** [comment]
You probably meant the height, not the width.

"LXQt Appearance Configuration" remembers its size but "Keyboard and Mouse Settings" dialog doesn't. We can't avoid scrollbars at the first run because different users may have different styles/fonts/... but we can remember the dialog size.

I'm changing the title and reopening this....

**Comment by ianfarrell47** [comment]
Should the height be corrected to something more reasonable? I understand now that the width/height is dynamic (corresponding to the font size). The default window dimensions appear to be the same as the minimum dimensions. Perhaps we could increase minimum dimensions to a height more reasonable.

**Comment by tsujan** [comment]
Searching for a "reasonable default height" isn't reasonable.
