### ISSUE TITLE
lxqt-config-locale - "No change" item bug

### ISSUE THREAD

**Issue by ianfarrell47** [lxqt/lxqt-config#824]
**Some things I have noticed from using lxqt-config-locale:**

~~There is an animation for list item clear icons... why? I believe from launching the program again and again, that the animation is causing performance issues.~~

Also "No change" appears to be broken, when selecting Detailed Settings.
Under the Examples section I get:
(for United States - American English (en_US)):
1,000.1; Sunday, March 13, 2022 12:34:42 AM EST; $24; Imperial US
(for Detailed Settings checked and all boxes set to No Change):
1000.1; Sunday, 13 March 2022 00:36:36 EST; 24; Metric

##### System Information
* Distribution & Version: Arch Linux
* Kernel: optiplex 5.16.14-zen1-1-zen
* Qt Version: qt5-base: 5.15.3+kde+r133-1
* liblxqt Version: 1.0.0-1
* lxqt-build-tools Version: 1.0.0-1
* Package version: 1.0.0.27.g5ac9f9e-1 5ac9f9e

**Comment by stefonarch** [comment]
I'm quite sure there is none, never saw this. Could be a compositor effect on your installation?
And for the second one: those are the actual settings shown and those  would be taken on save - there is no issue too.



![schermata-03-13-08-01](https://user-images.githubusercontent.com/10681413/158049207-7f52a1a8-58cd-4586-82a0-95d4b5aa4af3.png)

**Comment by tsujan** [comment]
> There is an animation for list item clear icons... why?

You're asking about what happens inside Qt. The answer is in Qt's code. *We* don't add any animation; Qt does.

**Comment by ianfarrell47** [comment]
I see the bug is much more narrow than I initially wrote. Because No Change indeed makes undefined changes, the initial values of Detailed Settings items should copy Region.

**Comment by ianfarrell47** [comment]
Because my words seem to be failing me, here's a screenshot
![screenshot1](https://user-images.githubusercontent.com/96850319/158067592-7dae6da4-716a-41ac-b882-9e8188ea25ad.png)
.

**Comment by stefonarch** [comment]
Thanks, I never saw this "no change", how did you produce it?

**Comment by ianfarrell47** [comment]
I believe No change is the default for unsaved LXQt locale settings under Detailed Settings

**Comment by stefonarch** [comment]
No, I tried different edits and cannot produce this. Can you describe step by step how you get this screen?

**Comment by ianfarrell47** [comment]
I just deleted `.config/lxqt/lxqt-config-locale.conf` and started lxqt-config-locale - Detailed Settings was checked and all options matched my Region, United States - American English (en_US). Somehow when I started lxqt-config-locale once the Detailed Settings was unchecked and all grayed out options under it were to set to No changes. Nevertheless, to reproduce and test the bug, select the first item in the list for items under Detailed Settings, it should be 'No change'.

**Comment by stefonarch** [comment]
Still cannot reproduce - I find no way to see this  "no change" here, but I see it in the source code and the translations.

**Comment by ianfarrell47** [comment]
Odd, the first option for me in the Detailed Settings lists are 'No change'.

**Comment by tsujan** [comment]
I see them. Had never paid attention to them because I only use US En.

Reopening...

**Comment by ianfarrell47** [comment]
Also regarding lxqt-config-locale, the padding of the window around all its elements is larger than the rest of lxqt-config binaries. I don't know if this is a feature or a bug, but I believe it could look nicer with "container boxes" and smaller padding. Taken from another binary in lxqt-config: (as an example of a "container box")
![screenshot](https://user-images.githubusercontent.com/96850319/158073813-42103471-dbba-4910-9dd0-cf11d0f3b21b.png)
Why, I apologize for my outstanding ignorance of programming; I am a long time LXDE/LXQt user who dabbles, but only a bit, in C++ programming. The complexity of C++ compared to C is overwhelming to me. I see so much potential in Qt for Linux, and LXQt is my favorite GUI environment for Linux/Unix. The work being done in the LXQt project is enabling vanilla Qt to shine, and offers a great alternative to KDE without losing much functionality. I plan on learning Qt6 and helping out more besides submitting issues. The work tsujan has been doing to the GUI is great, and, the seemingly trivial Qt GUI changes matter a lot to casual users like me.

**Comment by tsujan** [comment]
> Also regarding lxqt-config-locale, the padding of the window around all its elements is larger than the rest of lxqt-config binaries

Such things neither are bugs nor cause problems. They can be changed very easily but, I guess, devs respect the harmless choices of the original author of the app and don't touch them.

**Comment by ianfarrell47** [comment]
Yes, I was unsure if it was a feature or a bug - perhaps neither, as you said, a harmless design choice by the original authors. I still think a container box would be an improvement around Detailed Settings and Examples. I don't know how hard this is to implement these things in Qt.

**Comment by tsujan** [comment]
> I still think a container box....

It isn't about a box. The original author has added two 16-px horizontal spacers. Why? I don't know. I'll remove them later — if I don't forget them ;)

**Comment by tsujan** [comment]
> ... a container box would be an improvement around Detailed Settings and Examples. I don't know how hard this is to implement these things in Qt.

It's a piece of cake. I thought you meant the padding (→ my previous comment).

**Comment by ianfarrell47** [comment]
I spent some time in Qt Designer and came up with this. It looks okay in Qt Designer but surely I've made a couple of mistakes.
[localeconfig.ui.txt](https://github.com/lxqt/lxqt-config/files/8382766/localeconfig.ui.txt)

**Comment by tsujan** [comment]
I found time to check GUI as well as the code. There's no bug here; the GUI is OK:

 1. If you don't check "Detained Settings", the info of the "Region" combo will be used for Number, Time, etc.
 2. If you check that box, the info in the enabled combos will be used. The default is "No change", which means the value of the related environment variable (`LC_NUMERIC`, `LC_TIME`, etc.). If that environment variable is empty, the "C" locale will be used, which is the logical choice (made by Qt devs).

The "Detained Settings" box is for users who want to fine-tune their locale. Most users may only need to leave it unchecked, so that the "Region" combo is used for all details.
