### ISSUE TITLE
Appearance Config: Distinguish user themes and open theme folders

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt-config#852]
Inspired by my discussion with @stefonarch at the end of this page (the PR was reversed later): https://github.com/lxqt/liblxqt/pull/308

 1. Themes are always sorted alphabetically.
 2. User themes are distinguished by "(User Theme)" after their names.
 3. Double clicking a theme opens its folder.
 4. Also, each theme has a context menu for opening its folder.

A screenshot:

![themes](https://user-images.githubusercontent.com/981076/167445912-9c1425c4-2fd6-4538-af07-8c3f23f8de20.png)

**Comment by stefonarch** [comment]
That looks fine!
BTW I was never happy with "Override user-defined wallpaper". What about changing it to "Use  wallpaperprovided by the theme" ?

**Comment by tsujan** [comment]
Good idea. Would you make a PR for it?

**Comment by stefonarch** [comment]
→ https://github.com/lxqt/lxqt-config/pull/853

**Comment by ianfarrell47** [comment]
I'm looking forward to this in 1.1.1 or 1.2.0.

One other bit of polish on this panel that I see, for lack of a better spot to mention it, is to have consistent preview images. I can create an Issue and compile those images, and get it into 1.1.1 or 1.2.0, granted Git doesn't give me any issues.

**Comment by stefonarch** [comment]
Nice idea! I was thinking (related to making themes translatable) having also a description, but at the end it's not so important as users see quite immediately how the theme is.

And there is a not so small part of users that never touch themes ;) - I know some of theme.

**Comment by tsujan** [comment]
> I was thinking (related to making themes translatable) having also a description, but at the end it's not so important

I think we should do it before 1.1.2. Having a desktop entry for each theme has also this advantage that the theme name can be changed without changing its folder name, the latter being backward incompatible.

**Comment by ianfarrell47** [comment]
The .desktop files I feel are an okay idea, my only confusion there is that .desktop is typically used for launching applications, whereas raw data is typically stored in an INI.

I assumed the preview images were PNGs but I do not see them in the repository.

**Comment by tsujan** [comment]
> my only confusion there is that .desktop is typically used for launching applications

My mistake; sorry! It can be `index.theme`.

**Comment by stefonarch** [comment]
> I assumed the preview images were PNGs but I do not see them in the repository.

https://github.com/lxqt/lxqt-themes/blob/master/themes/Arch-Colors/preview.png

So ` theme.yaml` and `theme_de.yaml`in the first, while `index.theme` would be

```
Name=Ambiance
Comment=some description
Name[ar]= التطبيقات
Comment[ar]=قائمة لكل تطبيقاتك
Name[bg]=Стартово 
Comment[bg]=меню с всички ваши приложения
...
```

?

**Comment by tsujan** [comment]
> while index.theme would be

Yes, that's good. The description could be shown as the tooltip if existing.
