### ISSUE TITLE
"ApplicationChooser" is not a good name

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt-config#860]
In File Associations → Associations, if you select a mimetype from the left tree and press "Change..." or "Choose..." in the right pane, the "ApplicationChooser" dialog will be opened. That name may be good for C++ coding but not for appearing inside a GUI.

Please change it to "Application Chooser" — just add a space.

**Comment by stefonarch** [comment]
As it doesn't remember window size I never saw it. It looks also that it's impossible to reduce empty space in the title bar.

![schermata-21 mag 09:07](https://user-images.githubusercontent.com/10681413/169640289-84a70aa8-a119-48e3-b006-555f87e77df7.png)

![schermata-21 mag 09:08](https://user-images.githubusercontent.com/10681413/169640292-cb812bd7-e645-4745-9339-74b0939965f1.png)

**Comment by tsujan** [comment]
>  It looks also that it's impossible to reduce empty space in the title bar

That depends on the WM and its settings, not on the app.

![appchooser](https://user-images.githubusercontent.com/981076/169647809-a2ad09d9-ec41-4cb8-95e4-a9653cd21fb9.png)

**Comment by tsujan** [comment]
If we want to preserve the current translations (is there any?), we should edit the ts files manually. Could you do that? Or will it be OK if they disappear and are added by translators again?

**Comment by stefonarch** [comment]
> is there any?)
Yes
https://translate.lxqt-project.org/search/lxqt-configuration/?offset=1&q=applicationchooser&sort_by=-priority%2Cposition&checksum=

We have  working bash scripts which will remove the "type unfinished" which we used already twice already.
` sed -i '/></! s/translation\ type=\"unfinished\"/translation/g'  *.ts 
 `
or
`sed --in-place -re '/<translation .*type="unfinished"[^>]*>[^<]/ s/ ?type="unfinished"//' *_*.ts`

**Comment by stefonarch** [comment]
Looking closer at the translations some seems to have adopted the style:
"ВибирачПрограм" , "PemilihAplikasi"

**Comment by tsujan** [comment]
That's up to the translator to decide what sounds natural in his language. But "ApplicationChooser" seems like a copy-pase typo; it's the class name ;)

**Comment by ianfarrell47** [comment]
With the fixed title "Application Chooser" perhaps should be moved to liblxqt because it deals with platform integration? Pcmanfm's "File Properties" dialog when you click on "Open With" is similar functionality, though not tied to a MIME type.

**Comment by isf63** [comment]
I was thinking of adding the space to https://github.com/lxqt/lxqt-config/blob/bfd534bb5d6679077c448d5109ddad43f35278f6/lxqt-config-file-associations/applicationchooser.ui#L14
but because it's not a `tr( )` I got confused. I'm guessing all `<name>ApplicationChooser</name>` and `<source>ApplicationChooser</source>` in lxqt-config-file-associations/translations/* must be updated as well?

**Comment by tsujan** [comment]
> because it's not a tr( ) I got confused

All strings (`<string>...</string>`) in the ui file are translatable automatically — unless `<string notr="true">` is added.

> and <source>ApplicationChooser</source> in lxqt-config-file-associations/translations/* must be updated as well?

@stefonarch does it once in a while — shouldn't be done in PRs.

If you don't make PR, it'll be forgotten ;)  Please just add a space there; no other change is needed
