### ISSUE TITLE
AppimageLauncher configuration is shown under LXQt

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-config#868]
![schermata-25 giu 18:26](https://user-images.githubusercontent.com/10681413/175782391-22f5bb5a-7725-4379-9e3e-caa20b6a3613.png)

##### Expected Behavior

Should be shown under "system" or "other".

```

$ cat /usr/share/applications/appimagelaunchersettings.desktop 

[Desktop Entry]
Version=1.0
Type=Application
Exec=AppImageLauncherSettings %f
Name=AppImageLauncher Settings
Name[de]=AppImageLauncher-Einstellungen
Comment=Change settings for AppImageLauncher
Comment[de]=Einstellungen für AppImageLauncher ändern
Icon=AppImageLauncher
Terminal=false
Categories=Utility;Settings;DesktopSettings;LXQt;X-XFCE-SettingsDialog;X-XFCE-PersonalSettings;X-GNOME-PersonalSettings;
X-AppImage-Integrate=false
StartupWMClass=AppImageLauncher

```

##### Possible Solution

Tweak menu settings for this case.

##### Steps to Reproduce (for bugs)

1.  Install appimagelauncher
2.  Open Configuration Center

* Distribution & Version: latest arch and git

**Comment by tsujan** [comment]
They've added LXQt (and XFCE and GNOME) to their categories. That isn't something LXQt can change or control.

**Comment by stefonarch** [comment]
Sure, but we can make an rule for it.

**Comment by tsujan** [comment]
When I didn't know what LXQt was, an LXQt user asked me to put Kvantum Manager in the LXQt section of its config center, and he told me how. I agreed. Later, when I started to use LXQt, I had more reason for it.

I mean that (1) the rule has existed since the early versions of LXQt, and (2) developers are free to use it. Why should we take it away from them? Yes, some people may abuse it, but, IMHO, it's not our responsibility to prevent that.

**Comment by stefonarch** [comment]
It's not abuse here, but I don't see any relation of  those settings to LXQt Desktop, arguing like that also printer or firewall or anything else can go under LXQt.

**Comment by tsujan** [comment]
I agree.

I found this: https://github.com/TheAssassin/AppImageLauncher/pull/329#issuecomment-626368375. Apparently, it was just copied from the desktop file of Kvantum Manager!

Kvantum is tuned toward LXQt — its has codes related to pcmanfm-qt and LXQt main menu — and Kvantum Manager is a versatile tool for customizing LXQt's look. IMO, that copy-pasting was a mistake.

**Comment by stefonarch** [comment]
I see. With` Categories=Settings;DesktopSettings;X-XFCE-SettingsDialog;X-XFCE-PersonalSettings;X-GNOME-PersonalSettings;` it's shown under "Preferences" and "others settings in Config  Center. `Utility;` has to be removed  for this too.
