### ISSUE TITLE
lxqt-config-file-associations : weird behaviour, cannot change association

### ISSUE THREAD

**Issue by fenugrec** [lxqt/lxqt-config#897]
##### Expected Behavior
It should be fairly straightforward to change file associations. Current example is with `text/csv` files.

##### Current Behavior
- can't associate to a program listed in the `Applications that handle CSV documents` category
- for every attempt at setting Calc as the application, it adds a duplicate entry for Krita in the `Other Applications`category !
![assoc-1](https://user-images.githubusercontent.com/10098613/201950087-3fec35be-a219-4fa2-8c5d-a63a691d1fcc.gif)

[EDIT - second screenshot, scrolling down the ApplicationChooser dialog] 

![assoc-2](https://user-images.githubusercontent.com/10098613/201950088-3e9cc84a-aebb-48ae-b56a-79acf73183cb.gif)

##### Possible Solution
- workaround : edit mimeapps.list / lxqt-mimeapps.list  manually ...
 

##### Steps to Reproduce (for bugs)
1. get annoyed by a program "stealing" file associations from another that was there before
2. run lxqt-config-file-associations
3. try to change association : UI does nothing, unless I pick some random application in the "Other Applications" category. In the screenshots below, I was able to do that and assign Notepad (from wine...). If I try to assign Krita or Calc again, it doesn't do anything
4. Enjoy opening .csv files in notepad now !

##### System Information

* Distribution & Version:  Arch
* Kernel:  6.0.2
* Qt Version: 6.4.0
* liblxqt Version: 1.1.0
* lxqt-build-tools Version:  n/a
* Package version: 1.1.0

**Comment by fenugrec** [comment]
Additional information I just noticed while typing up the issue :

- running `xdg-open $csvfile_whatever` from the console opens it using Calc
- double-clicking the same .csv file from pcmanfm-qt  opens it in notepad

**Comment by tsujan** [comment]
Thanks for the report.

 1. For some reason, Calc can't be assigned. I can confirm that.
 2. Two `ApplicationChooser` dialogs are possible, which isn't right.

I can't confirm the duplication of Kriita under `Other Applications` with V1.2.0: There are 22 Krita items there, and their number always remain 22 (that's a weird choice of Krita — see `/usr/share/applications`).

**Comment by fenugrec** [comment]
>     2. Two `ApplicationChooser` dialogs are possible, which isn't right.

Sorry, my post wasn't very clear, that's actually 2 attachments , so 2 screenshots - I couldn't show everything in one.

>  There are 22 Krita items there, and their number always remains 22 (that's a weird choice of Krita — see `/usr/share/applications`).

Ah, I hadn't actually counted them - it just seemed like I tried about 20 times, so it seemed about right P)
Indeed, I have 23 krita_*.desktop files in `/usr/share/applications` !

**Comment by tsujan** [comment]
Anyway, the behavior you detected shows that there's a bug somewhere. And I agree: it's very weird.

**Comment by tsujan** [comment]
I haven't look into the code yet but the problem should be in `libqtxdg` because `pcmanfm-qt` has no problem in setting Calc as the default application for `text/csv`, while `qtxdg-mat` doe:

```
$ qtxdg-mat defapp text/csv -s libreoffice-calc.desktop
Could not set '/usr/lib/libreoffice/share/xdg/calc.desktop' as default for 'text/csv'
```

**Comment by tsujan** [comment]
→ https://github.com/lxqt/libqtxdg/issues/287

**Comment by fenugrec** [comment]
Thanks ! I will need to rebuild all lxqt-* packages to test this, so it may take a bit before I get time to do so.

**Comment by tsujan** [comment]
> I will need to rebuild all lxqt-* packages

If you had LXQt 1.2.0, you would just need to apply the patch at https://github.com/lxqt/libqtxdg/pull/288. But yes, with 1.1.0, you have to upgrade.

I tested it here, and it worked fine.
