### ISSUE TITLE
LXQt cursor setting doesn't work after an Arch/Manjaro upgrade

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt-config#900]
My cursor has been "ComixCursors-White" for years. I'd set it with LXQt Appearance Configuration, which had created `~/.icons/default/index.theme` as:

```
# Written by lxqt-config-appearance
[Icon Theme]
Name=Default
Comment=Default cursor theme
Inherits=ComixCursors-White
Size=24
```

After an Arch/Manjaro upgrade and a reboot, my default cursor changed to Adwaita. Resetting it to ComixCursors-White had no effect: after login, it became Adwaita again.

I went through the upgrade log and found out that a new package was installed last night, namely, `default-cursors`, which is a new dependency for ` libxcursor` and `wayland`. It created `/usr/share/icons/default/cursors` as a symlink to `/usr/share/icons/Adwaita/cursors`.

I succeeded in restoring ComixCursors-White only by creating `~/.local/share/icons/default/cursors` as a symlink to `/usr/share/icons/ComixCursors-White/cursors`.

##### Possible Solution

It seems that now, `lxqt-config-appearance` needs to create such a symlink, in addition to `~/.icons/default/index.theme`.

##### System Information

* Latest git LXQt

**Comment by tsujan** [comment]
I found that, with `/usr/share/icons/default/cursors` existing, creating `~/.local/share/icons/default/cursors` wasn't a real solution because the cursor reverted to Adwaita when the pointer was on KWin's title-bar. What really worked was `~/.icons/default/cursors` as a symlink and then, a logout and login.

Anyway, with the above-mentioned change, LXQt Appearance Configuration shows "Default" as the selected cursor theme. That's not good.

Even if the creation of `/usr/share/icons/default/cursors` with `default-cursors` and the removal of `/usr/share/icons/default/index.theme` from `libxcursor` are Arch-specific decisions, the cursor setting code of LXQt Appearance Configuration may have a problem that's triggered by the existence of `/usr/share/icons/default/cursors`, because I didn't see any issue under KDE.

**Comment by tsujan** [comment]
> it that arch-specific?

Yes, it is. But I still wonder why KDE has no problem with it.

**Comment by stefonarch** [comment]
Maybe because of that breeze package?

```
$ yay -Ss default-cursor
aur/breeze-default-cursor-theme 2.0-3 (+4 0.00) 
    Breeze Default Cursor Theme.
extra/default-cursors 1-1 (2.1 KiB 0.0 B) (Installed)
    Default cursor set
```

**Comment by stefonarch** [comment]
I've restarted the session, and I've "my" cursor" only in gtk applications. 

Going for `rm  /usr/share/icons/default/cursors ` atm.

**Comment by tsujan** [comment]
The change has been reversed in `default-cursors-2-1`.
