### ISSUE TITLE
Help: list all configuration file path

### ISSUE THREAD

**Issue by QiangF** [lxqt/lxqt-config#902]
I was expecting all configurations under ~/.config/lxqt. But in lxqt-config-session, the manually added command and command name in "Global Autostart" is not saved in that folder. Where is that setting saved?

And we have pcmanfm config under ~/.config/pcmanfm-qt/lxqt. Why not put them all in one place?

Many people use symlinks to manage dotfiles, (https://github.com/lxqt/lxqt-config/issues/740) Clicking around to get all settings is not fun. If lxqt can be configured with text files or command line (https://github.com/lxqt/lxqt-config/issues/597), it will attract more users.  :-)

**Comment by tsujan** [comment]
LXQt is modular, and pcmanfm-qt can be used under any DE, independently of LXQt. That's also true for lxqt-archiver, lximage-qt,.... Also, auto-start has its standard config folder.

Config files aren't for manual editing by average users. Advanced users have to find them themselves and know how to deal with them, at their own risk. That's true for all apps.

**Comment by QiangF** [comment]
@tsujan Can you please give a hint on where the manually added command and command name in "Global Autostart" is saved?

**Comment by QiangF** [comment]
I am not editing the file, just want to sync across computers. Config files need to be put in a safe place, there is no safter place than a git repo.

**Comment by stefonarch** [comment]
> @tsujan Can you please give a hint on where the manually added command and command name in "Global Autostart" is saved? I know the desktop file are in /etc/xdg/autostart and ~/.config/autostart. I can't find the autostart for command that doesn't have a desktop file.

Inactive autostart entries are  made hidden  in `~/.config/autostart`, desktop files will be created there if  adding manually.

**Comment by QiangF** [comment]
No, my autostart entry is active. It's a command I added, the command is just emacs.

**Comment by QiangF** [comment]
Sorry it is in ~/.config/autostart. I should have double checked.

**Comment by tsujan** [comment]
As for the auto-start, please note that it isn't specific to LXQt. There can be other items from other DEs in it. The value of `OnlyShowIn` inside each desktop entry determines under which DE it's active.
