### ISSUE TITLE
how to add external shortcuts to lxqt

### ISSUE THREAD

**Issue by fadi123go** [lxqt/lxqt-config#917]
how to add external shortcuts to lxqt-config.  I want to add xfwm4 settings and tweaks to it

**Comment by stefonarch** [comment]
Please don't open issues for questions, converting in discussion.

**Comment by stefonarch** [comment]
@tsujan I don't see the button "convert to discussion" here.

**Comment by fadi123go** [comment]
I meant how to add them to lxqt control center. I know how to do what is the wiki page.

**Comment by tsujan** [comment]
> @tsujan I don't see the button "convert to discussion" here.

There isn't any button. Only issues opened at https://github.com/lxqt/lxqt/issues can be converted to discussions.

**Comment by fadi123go** [comment]
Thanks a lot to your help @tsujan . I managed to do what I wanted to do and sorry for troubling you.
