### ISSUE TITLE
[lxqt-config-monitor] primary monitor setting doesn't work properly

### ISSUE THREAD

**Issue by Loader009** [lxqt/lxqt-config#925]
##### Expected Behavior

Primary monitor should be set - monitor number should not change.
##### Current Behavior

Primary monitor seems to always be the last monitor - the conf file shows - all monitors are "primary".
##### Steps to Reproduce (for bugs)

1. open lxqt-config-monitor
2. set another primary monitor and save/apply
3. close lxqt-config-monitor
4. open it again and check again

##### Context

After some update in the last few months I had to rearrange my panels due to wrong monitor number/order.
Some fullscreen applications only open on the primary display, which is currently not the one I actually use as my main display (a total of three displays connected).
##### System Information

* Distribution & Version: archlinux
* Kernel: 6.2.2-zen2-1-zen
* Qt Version: 5.15.8
* liblxqt Version: 1.2.0-1
* Package version: 1.2.0-1
--- I don't use AUR for lxqt anymore! ---

**Comment by tsujan** [comment]
OK, the bug is in `libkscreen` 5.27.2.

The methods that worked fine were in `libkscreen` 5.26.5:

```c++
bool Output::isPrimary() const
{
    return d->primary;
}

void Output::setPrimary(bool primary)
{
    if (d->primary == primary) {
        return;
    }

    d->primary = primary;

    Q_EMIT isPrimaryChanged();
}
```

Now, these are their corresponding methods in `libkscreen` 5.27.2:

```c++
bool Output::isPrimary() const
{
    return d->enabled && (d->priority == 1);
}

void Output::setPrimary(bool primary)
{
    setPriority(1);
}
```

`setPrimary()` ignores its argument. My guess is that it's an incomplete draft that has popped up in the release by mistake (they have a plan to give priority to outputs, instead of making one of them primary).

**Comment by tsujan** [comment]
The problems still exists in git.

I think we need to change the code based on output priorities, but it may be too soon for that.

**Comment by Loader009** [comment]
I actually don't think that they have it on the screen -> https://bugs.kde.org/buglist.cgi?component=libkscreen&product=KScreen&resolution=---
I might try to downgrade the lib and lxqt-config instead.

**Comment by Loader009** [comment]
Getting an error when I run lxqt-config-monitor (even after recompilation with libkscreen 5.26.5):
```
org.kde.kscreen: Invalid key in Output map:  "priority"
Connecting to KScreen...
Error: Config is invalid, probably backend couldn't load
```

I guess there are more changes, I'll reverse my changes for now.

**Comment by Loader009** [comment]
fyi, I have filed a bug report at KDE
https://bugs.kde.org/show_bug.cgi?id=471195

**Comment by tsujan** [comment]
> fyi, I have filed a bug report at KDE

Thanks! At least they'll know that it's used outside KDE too.

**Comment by Loader009** [comment]
As a workaround - use ARandR to create a xrandr script for the correct primary display - you could execute it every time you reboot.
Just know that you have to change lxqt-panel configs (placement) once (and back), so the panels are on their correct place.

Since I switch between two places, I need two different layouts, so I use those scripts to have the correct display layout every time I move.

**Comment by Loader009** [comment]
@tsujan -> https://github.com/KDE/libkscreen/commit/68a389c717ad97d2f57f534040ecdf8458f8e8b0
_    New API is meant to replace previous one, but old one is still kept for compatibility and convenience (and to let you shoot yourself in the foot when you least expect it). If you ever use `Output::setPrimary()` or `Output::setPriority()` after adding one to a config, here be dragons. You've been warned._

Are there reasons to be concerned?
Maybe the "bug" was introduced to get people to migrate to a "new API"?

**Comment by ratijas** [comment]
Oh hi. I apologize for the mistake we made during refactoring.

> setPrimary() ignores its argument. My guess is that it's an incomplete draft that has popped up in the release by mistake

Less like a draft, and more like a rotten piece that was left around unused by libkscreen and thus untested. 🥴

The call to `setPriority(1)` should be guarded by an `if (primary)` condition. But there's not much meaningful we can do for the reverse `!primary` case.

> they have a plan to give priorities to outputs, instead of making one of them primary

Indeed, the new and more robust way is to set priorities, which are also maintained to be unique and sequential by the Config object. One should not call priority-related methods on Outputs directly. I wanted to make them protected from outside access (`friend class Config`)  but that proposal got rejected.

>  Maybe the "bug" was introduced to get people to migrate to a "new API"?

Most certainly not. But if your code calls `Output::setPrimary`, it better be ported to `config->setPrimaryOutput`

**Comment by Loader009** [comment]
@tsujan Are you still active?
This issue could be solved quickly.

**Comment by tsujan** [comment]
> Are you still active?

Busy with other codes.

> This issue could be solved quickly

II also thought so when writing https://github.com/lxqt/lxqt-config/issues/925#issuecomment-1465913912).

I'll try to find time for it before the next release in November, but if you have a patch, please make a PR.

**Comment by ratijas** [comment]
Hey, it was patched literally the same day and backported. I don't know why this issue is still open. Is this still a problem you experience?

https://invent.kde.org/plasma/libkscreen/-/merge_requests/143

**Comment by Loader009** [comment]
@ratijas you are right, it's fixed in the ArchLinux package (libkscreen) from 1. Aug.
Thanks for the hint!
(I didn't check it before, since it took quite some time until the package was updated.)

Meaning, we could close the issue - or let it open to have @tsujan clean the code?

**Comment by tsujan** [comment]
> it was patched literally the same day...

I meant *our* code ;)

**Comment by tsujan** [comment]
Made a PR: https://github.com/lxqt/lxqt-config/pull/954. Also, bumped the min. required version of `libkscreen` to `5.27.0`.
