### ISSUE TITLE
Center configuration windows under wayland

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-config#984]
On X11 most `(lxqt-admim-* ` are not)  Qt configuration windows are centered on the screen, on wayland they open depending on the compositor. This affects also other elements in other repositories like "configure panel". 

This particularly important when using tiling WM like sway or Hyprland, otherwise they will get tiled and eventually fullscreen.

##### Expected Behavior

Same behaviour as in X11

##### Possible Solution

Add layershell code in those windows, similar to lxqt-runner or lxqt-leave.

##### System Information

* Distribution & Version: latest git
* Qt Version: 6.6
* liblxqt Version: 2.0

**Comment by tsujan** [comment]
IMO, we shouldn't do that. Unless a dialog really needs attention (like lxqt-leave dialog), we shouldn't force a position/layer on it by using layer-shell-qt. In general, we shouldn't overuse layer-shell-qt.

Qt centers all parentless dialogs under X11. Whether a Wayland WM can distinguish between dialogs and ordinary windows and have an option for positioning the former is another question, whose answer is outside LXQt.

**Comment by tsujan** [comment]
Then `kwin_wayland` somehow distinguishes parentless Qt dialogs and centers them to mimic Qt under X11.

**Comment by stefonarch** [comment]
Centering with layershell would exclude them from pager and taskbar.
